/**
 *
 * @file CRC_RegisterDefines_CTL1.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 6 feb. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 6 feb. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef CRC_PERIPHERAL_REGISTERDEFINES_HEADER_CRC_REGISTERDEFINES_CTL1_H_
#define CRC_PERIPHERAL_REGISTERDEFINES_HEADER_CRC_REGISTERDEFINES_CTL1_H_

#include <xDriver_MCU/CRC/Peripheral/xHeader/CRC_Enum.h>

/******************************************************************************************
 ************************************ 1 CTL1 *********************************************
 ******************************************************************************************/

#define CRC_CTL1_CHTSEL_MASK ((UBase_t) 0x1FU)
#define CRC_CTL1_CHTSEL_SW ((UBase_t) 0U)
#define CRC_CTL1_CHTSEL_TA0CCR0 ((UBase_t) 1U)
#define CRC_CTL1_CHTSEL_TA0CCR2 ((UBase_t) 2U)
#define CRC_CTL1_CHTSEL_TA2CCR0 ((UBase_t) 3U)
#define CRC_CTL1_CHTSEL_TA2CCR2 ((UBase_t) 4U)
#define CRC_CTL1_CHTSEL_UCA0_RX ((UBase_t) 16U)
#define CRC_CTL1_CHTSEL_UCA0_TX ((UBase_t) 17U)
#define CRC_CTL1_CHTSEL_UCB0_RX ((UBase_t) 18U)
#define CRC_CTL1_CHTSEL_UCB0_TX ((UBase_t) 19U)
#define CRC_CTL1_CHTSEL_ADC12x ((UBase_t) 24U)
#define CRC_CTL1_CHTSEL_MPY ((UBase_t) 29U)
#define CRC_CTL1_CHTSEL_CRC ((UBase_t) 30U)
#define CRC_CTL1_CHTSEL_EXTERNAL ((UBase_t) 31U)

/*-----------*/
#define CRC_CTL1_R_CH2TSEL_BIT ((UBase_t) 0U)

#define CRC_CTL1_CH2TSEL_MASK ((UBase_t) 32U)
#define CRC_CTL1_CH2TSEL_SW ((UBase_t) 0U)
#define CRC_CTL1_CH2TSEL_TA0CCR0 ((UBase_t) 1U)
#define CRC_CTL1_CH2TSEL_TA0CCR2 ((UBase_t) 2U)
#define CRC_CTL1_CH2TSEL_TA2CCR0 ((UBase_t) 3U)
#define CRC_CTL1_CH2TSEL_TA2CCR2 ((UBase_t) 4U)
#define CRC_CTL1_CH2TSEL_UCA0_RX ((UBase_t) 16U)
#define CRC_CTL1_CH2TSEL_UCA0_TX ((UBase_t) 17U)
#define CRC_CTL1_CH2TSEL_UCB0_RX ((UBase_t) 18U)
#define CRC_CTL1_CH2TSEL_UCB0_TX ((UBase_t) 19U)
#define CRC_CTL1_CH2TSEL_ADC12x ((UBase_t) 24U)
#define CRC_CTL1_CH2TSEL_MPY ((UBase_t) 29U)
#define CRC_CTL1_CH2TSEL_CRC ((UBase_t) 30U)
#define CRC_CTL1_CH2TSEL_EXTERNAL ((UBase_t) 31U)

#define CRC_CTL1_R_CH2TSEL_MASK (CRC_CTL1_CH2TSEL_MASK << CRC_CTL1_R_CH2TSEL_BIT)
#define CRC_CTL1_R_CH2TSEL_SW (CRC_CTL1_CH2TSEL_SW << CRC_CTL1_R_CH2TSEL_BIT)
#define CRC_CTL1_R_CH2TSEL_TA0CCR0 (CRC_CTL1_CH2TSEL_TA0CCR0 << CRC_CTL1_R_CH2TSEL_BIT)
#define CRC_CTL1_R_CH2TSEL_TA0CCR2 (CRC_CTL1_CH2TSEL_TA0CCR2 << CRC_CTL1_R_CH2TSEL_BIT)
#define CRC_CTL1_R_CH2TSEL_TA2CCR0 (CRC_CTL1_CH2TSEL_TA2CCR0 << CRC_CTL1_R_CH2TSEL_BIT)
#define CRC_CTL1_R_CH2TSEL_TA2CCR2 (CRC_CTL1_CH2TSEL_TA2CCR2 << CRC_CTL1_R_CH2TSEL_BIT)
#define CRC_CTL1_R_CH2TSEL_UCA0_RX (CRC_CTL1_CH2TSEL_UCA0_RX << CRC_CTL1_R_CH2TSEL_BIT)
#define CRC_CTL1_R_CH2TSEL_UCA0_TX (CRC_CTL1_CH2TSEL_UCA0_TX << CRC_CTL1_R_CH2TSEL_BIT)
#define CRC_CTL1_R_CH2TSEL_UCB0_RX (CRC_CTL1_CH2TSEL_UCB0_RX << CRC_CTL1_R_CH2TSEL_BIT)
#define CRC_CTL1_R_CH2TSEL_UCB0_TX (CRC_CTL1_CH2TSEL_UCB0_TX << CRC_CTL1_R_CH2TSEL_BIT)
#define CRC_CTL1_R_CH2TSEL_ADC12x (CRC_CTL1_CH2TSEL_ADC12x << CRC_CTL1_R_CH2TSEL_BIT)
#define CRC_CTL1_R_CH2TSEL_MPY (CRC_CTL1_CH2TSEL_MPY << CRC_CTL1_R_CH2TSEL_BIT)
#define CRC_CTL1_R_CH2TSEL_CRC (CRC_CTL1_CH2TSEL_CRC << CRC_CTL1_R_CH2TSEL_BIT)
#define CRC_CTL1_R_CH2TSEL_EXTERNAL (CRC_CTL1_CH2TSEL_EXTERNAL << CRC_CTL1_R_CH2TSEL_BIT)
/*-----------*/

/*-----------*/
#define CRC_CTL1_R_CH3TSEL_BIT ((UBase_t) 8U)

#define CRC_CTL1_CH3TSEL_MASK ((UBase_t) 0x1FU)
#define CRC_CTL1_CH3TSEL_SW ((UBase_t) 0U)
#define CRC_CTL1_CH3TSEL_TA0CCR0 ((UBase_t) 1U)
#define CRC_CTL1_CH3TSEL_TA0CCR2 ((UBase_t) 2U)
#define CRC_CTL1_CH3TSEL_TA2CCR0 ((UBase_t) 3U)
#define CRC_CTL1_CH3TSEL_TA2CCR2 ((UBase_t) 4U)
#define CRC_CTL1_CH3TSEL_UCA0_RX ((UBase_t) 16U)
#define CRC_CTL1_CH3TSEL_UCA0_TX ((UBase_t) 17U)
#define CRC_CTL1_CH3TSEL_UCB0_RX ((UBase_t) 18U)
#define CRC_CTL1_CH3TSEL_UCB0_TX ((UBase_t) 19U)
#define CRC_CTL1_CH3TSEL_ADC12x ((UBase_t) 24U)
#define CRC_CTL1_CH3TSEL_MPY ((UBase_t) 29U)
#define CRC_CTL1_CH3TSEL_CRC ((UBase_t) 30U)
#define CRC_CTL1_CH3TSEL_EXTERNAL ((UBase_t) 31U)

#define CRC_CTL1_R_CH3TSEL_MASK (CRC_CTL1_CH3TSEL_MASK << CRC_CTL1_R_CH3TSEL_BIT)
#define CRC_CTL1_R_CH3TSEL_SW (CRC_CTL1_CH3TSEL_SW << CRC_CTL1_R_CH3TSEL_BIT)
#define CRC_CTL1_R_CH3TSEL_TA0CCR0 (CRC_CTL1_CH3TSEL_TA0CCR0 << CRC_CTL1_R_CH3TSEL_BIT)
#define CRC_CTL1_R_CH3TSEL_TA0CCR2 (CRC_CTL1_CH3TSEL_TA0CCR2 << CRC_CTL1_R_CH3TSEL_BIT)
#define CRC_CTL1_R_CH3TSEL_TA2CCR0 (CRC_CTL1_CH3TSEL_TA2CCR0 << CRC_CTL1_R_CH3TSEL_BIT)
#define CRC_CTL1_R_CH3TSEL_TA2CCR2 (CRC_CTL1_CH3TSEL_TA2CCR2 << CRC_CTL1_R_CH3TSEL_BIT)
#define CRC_CTL1_R_CH3TSEL_UCA0_RX (CRC_CTL1_CH3TSEL_UCA0_RX << CRC_CTL1_R_CH3TSEL_BIT)
#define CRC_CTL1_R_CH3TSEL_UCA0_TX (CRC_CTL1_CH3TSEL_UCA0_TX << CRC_CTL1_R_CH3TSEL_BIT)
#define CRC_CTL1_R_CH3TSEL_UCB0_RX (CRC_CTL1_CH3TSEL_UCB0_RX << CRC_CTL1_R_CH3TSEL_BIT)
#define CRC_CTL1_R_CH3TSEL_UCB0_TX (CRC_CTL1_CH3TSEL_UCB0_TX << CRC_CTL1_R_CH3TSEL_BIT)
#define CRC_CTL1_R_CH3TSEL_ADC12x (CRC_CTL1_CH3TSEL_ADC12x << CRC_CTL1_R_CH3TSEL_BIT)
#define CRC_CTL1_R_CH3TSEL_MPY (CRC_CTL1_CH3TSEL_MPY << CRC_CTL1_R_CH3TSEL_BIT)
#define CRC_CTL1_R_CH3TSEL_CRC (CRC_CTL1_CH3TSEL_CRC << CRC_CTL1_R_CH3TSEL_BIT)
#define CRC_CTL1_R_CH3TSEL_EXTERNAL (CRC_CTL1_CH3TSEL_EXTERNAL << CRC_CTL1_R_CH3TSEL_BIT)
/*-----------*/

#endif /* CRC_PERIPHERAL_REGISTERDEFINES_HEADER_CRC_REGISTERDEFINES_CTL1_H_ */
