/**
 *
 * @file SYSCTL_RegisterDefines_RSTIV.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 9 ene. 2023 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 9 ene. 2023     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_RSTIV_H_
#define XDRIVER_MCU_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_RSTIV_H_

#include "xDriver_MCU/SYSCTL/Peripheral/xHeader/SYSCTL_Enum.h"

/******************************************************************************************
 ************************************ 10 RSTIV *********************************************
 ******************************************************************************************/
/*-----------*/
#define SYSCTL_RSTIV_R_RSTVEC_BIT ((UBase_t) 0U)

#define SYSCTL_RSTIV_RSTVEC_MASK ((UBase_t) 0xFFFFU)
#define SYSCTL_RSTIV_RSTVEC_NOINTERRUPT ((UBase_t) 0x00U)
#define SYSCTL_RSTIV_RSTVEC_BROWNOUT ((UBase_t) 0x02U)
#define SYSCTL_RSTIV_RSTVEC_RST_NMI ((UBase_t) 0x04U)
#define SYSCTL_RSTIV_RSTVEC_PMMSWBOR ((UBase_t) 0x06U)
#define SYSCTL_RSTIV_RSTVEC_WAKEUP ((UBase_t) 0x08U)
#define SYSCTL_RSTIV_RSTVEC_SECURITY ((UBase_t) 0x0AU)
#define SYSCTL_RSTIV_RSTVEC_SVSL ((UBase_t) 0x0CU)
#define SYSCTL_RSTIV_RSTVEC_SVSH ((UBase_t) 0x0EU)
#define SYSCTL_RSTIV_RSTVEC_SVML_OVP ((UBase_t) 0x10U)
#define SYSCTL_RSTIV_RSTVEC_SVMH_OVP ((UBase_t) 0x12U)
#define SYSCTL_RSTIV_RSTVEC_PMMSWPOR ((UBase_t) 0x14U)
#define SYSCTL_RSTIV_RSTVEC_WDT_TIMEOUT ((UBase_t) 0x16U)
#define SYSCTL_RSTIV_RSTVEC_WDT_PASSWORD ((UBase_t) 0x18U)
#define SYSCTL_RSTIV_RSTVEC_FLASH_PASSWORD ((UBase_t) 0x1AU)
#define SYSCTL_RSTIV_RSTVEC_PERF ((UBase_t) 0x1EU)
#define SYSCTL_RSTIV_RSTVEC_PMM_PASSWORD ((UBase_t) 0x20U)

#define SYSCTL_RSTIV_R_RSTVEC_MASK (SYSCTL_RSTIV_RSTVEC_MASK<< SYSCTL_RSTIV_R_RSTVEC_BIT)
#define SYSCTL_RSTIV_R_RSTVEC_NOINTERRUPT (SYSCTL_RSTIV_RSTVEC_NOINTERRUPT << SYSCTL_RSTIV_R_RSTVEC_BIT)
#define SYSCTL_RSTIV_R_RSTVEC_BROWNOUT (SYSCTL_RSTIV_RSTVEC_BROWNOUT << SYSCTL_RSTIV_R_RSTVEC_BIT)
#define SYSCTL_RSTIV_R_RSTVEC_RST_NMI (SYSCTL_RSTIV_RSTVEC_RST_NMI << SYSCTL_RSTIV_R_RSTVEC_BIT)
#define SYSCTL_RSTIV_R_RSTVEC_PMMSWBOR (SYSCTL_RSTIV_RSTVEC_PMMSWBOR << SYSCTL_RSTIV_R_RSTVEC_BIT)
#define SYSCTL_RSTIV_R_RSTVEC_WAKEUP (SYSCTL_RSTIV_RSTVEC_WAKEUP << SYSCTL_RSTIV_R_RSTVEC_BIT)
#define SYSCTL_RSTIV_R_RSTVEC_SECURITY (SYSCTL_RSTIV_RSTVEC_SECURITY << SYSCTL_RSTIV_R_RSTVEC_BIT)
#define SYSCTL_RSTIV_R_RSTVEC_SVSL (SYSCTL_RSTIV_RSTVEC_SVSL << SYSCTL_RSTIV_R_RSTVEC_BIT)
#define SYSCTL_RSTIV_R_RSTVEC_SVSH (SYSCTL_RSTIV_RSTVEC_SVSH << SYSCTL_RSTIV_R_RSTVEC_BIT)
#define SYSCTL_RSTIV_R_RSTVEC_SVML_OVP (SYSCTL_RSTIV_RSTVEC_SVML_OVP << SYSCTL_RSTIV_R_RSTVEC_BIT)
#define SYSCTL_RSTIV_R_RSTVEC_SVMH_OVP (SYSCTL_RSTIV_RSTVEC_SVMH_OVP << SYSCTL_RSTIV_R_RSTVEC_BIT)
#define SYSCTL_RSTIV_R_RSTVEC_PMMSWPOR (SYSCTL_RSTIV_RSTVEC_PMMSWPOR << SYSCTL_RSTIV_R_RSTVEC_BIT)
#define SYSCTL_RSTIV_R_RSTVEC_WDT_TIMEOUT (SYSCTL_RSTIV_RSTVEC_WDT_TIMEOUT << SYSCTL_RSTIV_R_RSTVEC_BIT)
#define SYSCTL_RSTIV_R_RSTVEC_WDT_PASSWORD (SYSCTL_RSTIV_RSTVEC_WDT_PASSWORD << SYSCTL_RSTIV_R_RSTVEC_BIT)
#define SYSCTL_RSTIV_R_RSTVEC_FLASH_PASSWORD (SYSCTL_RSTIV_RSTVEC_FLASH_PASSWORD << SYSCTL_RSTIV_R_RSTVEC_BIT)
#define SYSCTL_RSTIV_R_RSTVEC_PERF (SYSCTL_RSTIV_RSTVEC_PERF << SYSCTL_RSTIV_R_RSTVEC_BIT)
#define SYSCTL_RSTIV_R_RSTVEC_PMM_PASSWORD (SYSCTL_RSTIV_RSTVEC_PMM_PASSWORD << SYSCTL_RSTIV_R_RSTVEC_BIT)
/*-----------*/




#endif /* XDRIVER_MCU_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_RSTIV_H_ */
