/**
 *
 * @file SYSCTL_RegisterDefines_JMBC.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 9 ene. 2023 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 9 ene. 2023     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_JMBC_H_
#define XDRIVER_MCU_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_JMBC_H_

#include "xDriver_MCU/SYSCTL/Peripheral/xHeader/SYSCTL_Enum.h"

/******************************************************************************************
 ************************************ 3 CTL *********************************************
 ******************************************************************************************/
/*-----------*/
#define SYSCTL_JMBC_R_JMBIN0FG_BIT ((UBase_t) 0U)

#define SYSCTL_JMBC_JMBIN0FG_MASK ((UBase_t) 0x01U)
#define SYSCTL_JMBC_JMBIN0FG_NONEW ((UBase_t) 0x00U)
#define SYSCTL_JMBC_JMBIN0FG_NEW ((UBase_t) 0x01U)

#define SYSCTL_JMBC_R_JMBIN0FG_MASK (SYSCTL_JMBC_JMBIN0FG_MASK<< SYSCTL_JMBC_R_JMBIN0FG_BIT)
#define SYSCTL_JMBC_R_JMBIN0FG_NONEW (SYSCTL_JMBC_JMBIN0FG_NONEW << SYSCTL_JMBC_R_JMBIN0FG_BIT)
#define SYSCTL_JMBC_R_JMBIN0FG_NEW (SYSCTL_JMBC_JMBIN0FG_NEW << SYSCTL_JMBC_R_JMBIN0FG_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_JMBC_R_JMBIN1FG_BIT ((UBase_t) 1U)

#define SYSCTL_JMBC_JMBIN1FG_MASK ((UBase_t) 0x01U)
#define SYSCTL_JMBC_JMBIN1FG_NONEW ((UBase_t) 0x00U)
#define SYSCTL_JMBC_JMBIN1FG_NEW ((UBase_t) 0x01U)

#define SYSCTL_JMBC_R_JMBIN1FG_MASK (SYSCTL_JMBC_JMBIN1FG_MASK<< SYSCTL_JMBC_R_JMBIN1FG_BIT)
#define SYSCTL_JMBC_R_JMBIN1FG_NONEW (SYSCTL_JMBC_JMBIN1FG_NONEW << SYSCTL_JMBC_R_JMBIN1FG_BIT)
#define SYSCTL_JMBC_R_JMBIN1FG_NEW (SYSCTL_JMBC_JMBIN1FG_NEW << SYSCTL_JMBC_R_JMBIN1FG_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_JMBC_R_JMBOUT0FG_BIT ((UBase_t) 2U)

#define SYSCTL_JMBC_JMBOUT0FG_MASK ((UBase_t) 0x01U)
#define SYSCTL_JMBC_JMBOUT0FG_NOREADY ((UBase_t) 0x00U)
#define SYSCTL_JMBC_JMBOUT0FG_READY ((UBase_t) 0x01U)

#define SYSCTL_JMBC_R_JMBOUT0FG_MASK (SYSCTL_JMBC_JMBOUT0FG_MASK<< SYSCTL_JMBC_R_JMBOUT0FG_BIT)
#define SYSCTL_JMBC_R_JMBOUT0FG_NOREADY (SYSCTL_JMBC_JMBOUT0FG_NOREADY << SYSCTL_JMBC_R_JMBOUT0FG_BIT)
#define SYSCTL_JMBC_R_JMBOUT0FG_READY (SYSCTL_JMBC_JMBOUT0FG_READY << SYSCTL_JMBC_R_JMBOUT0FG_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_JMBC_R_JMBOUT1FG_BIT ((UBase_t) 3U)

#define SYSCTL_JMBC_JMBOUT1FG_MASK ((UBase_t) 0x01U)
#define SYSCTL_JMBC_JMBOUT1FG_NOREADY ((UBase_t) 0x00U)
#define SYSCTL_JMBC_JMBOUT1FG_READY ((UBase_t) 0x01U)

#define SYSCTL_JMBC_R_JMBOUT1FG_MASK (SYSCTL_JMBC_JMBOUT1FG_MASK<< SYSCTL_JMBC_R_JMBOUT1FG_BIT)
#define SYSCTL_JMBC_R_JMBOUT1FG_NOREADY (SYSCTL_JMBC_JMBOUT1FG_NOREADY << SYSCTL_JMBC_R_JMBOUT1FG_BIT)
#define SYSCTL_JMBC_R_JMBOUT1FG_READY (SYSCTL_JMBC_JMBOUT1FG_READY << SYSCTL_JMBC_R_JMBOUT1FG_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_JMBC_R_JMBMODE_BIT ((UBase_t) 4U)

#define SYSCTL_JMBC_JMBMODE_MASK ((UBase_t) 0x01U)
#define SYSCTL_JMBC_JMBMODE_16BIT ((UBase_t) 0x00U)
#define SYSCTL_JMBC_JMBMODE_32BIT ((UBase_t) 0x01U)

#define SYSCTL_JMBC_R_JMBMODE_MASK (SYSCTL_JMBC_JMBMODE_MASK<< SYSCTL_JMBC_R_JMBMODE_BIT)
#define SYSCTL_JMBC_R_JMBMODE_16BIT (SYSCTL_JMBC_JMBMODE_16BIT << SYSCTL_JMBC_R_JMBMODE_BIT)
#define SYSCTL_JMBC_R_JMBMODE_32BIT (SYSCTL_JMBC_JMBMODE_32BIT << SYSCTL_JMBC_R_JMBMODE_BIT)
/*-----------*/


/*-----------*/
#define SYSCTL_JMBC_R_JMBCLR0OFF_BIT ((UBase_t) 6U)

#define SYSCTL_JMBC_JMBCLR0OFF_MASK ((UBase_t) 0x01U)
#define SYSCTL_JMBC_JMBCLR0OFF_HARDWARE ((UBase_t) 0x00U)
#define SYSCTL_JMBC_JMBCLR0OFF_SOFTWARE ((UBase_t) 0x01U)

#define SYSCTL_JMBC_R_JMBCLR0OFF_MASK (SYSCTL_JMBC_JMBCLR0OFF_MASK<< SYSCTL_JMBC_R_JMBCLR0OFF_BIT)
#define SYSCTL_JMBC_R_JMBCLR0OFF_HARDWARE (SYSCTL_JMBC_JMBCLR0OFF_HARDWARE << SYSCTL_JMBC_R_JMBCLR0OFF_BIT)
#define SYSCTL_JMBC_R_JMBCLR0OFF_SOFTWARE (SYSCTL_JMBC_JMBCLR0OFF_SOFTWARE << SYSCTL_JMBC_R_JMBCLR0OFF_BIT)
/*-----------*/


/*-----------*/
#define SYSCTL_JMBC_R_JMBCLR1OFF_BIT ((UBase_t) 7U)

#define SYSCTL_JMBC_JMBCLR1OFF_MASK ((UBase_t) 0x01U)
#define SYSCTL_JMBC_JMBCLR1OFF_HARDWARE ((UBase_t) 0x00U)
#define SYSCTL_JMBC_JMBCLR1OFF_SOFTWARE ((UBase_t) 0x01U)

#define SYSCTL_JMBC_R_JMBCLR1OFF_MASK (SYSCTL_JMBC_JMBCLR1OFF_MASK<< SYSCTL_JMBC_R_JMBCLR1OFF_BIT)
#define SYSCTL_JMBC_R_JMBCLR1OFF_HARDWARE (SYSCTL_JMBC_JMBCLR1OFF_HARDWARE << SYSCTL_JMBC_R_JMBCLR1OFF_BIT)
#define SYSCTL_JMBC_R_JMBCLR1OFF_SOFTWARE (SYSCTL_JMBC_JMBCLR1OFF_SOFTWARE << SYSCTL_JMBC_R_JMBCLR1OFF_BIT)
/*-----------*/

#endif /* XDRIVER_MCU_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_JMBC_H_ */
