/**
 *
 * @file TLV_RegisterAddress.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 20 ene. 2023 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 20 ene. 2023     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_TLV_PERIPHERAL_XHEADER_TLV_REGISTERADDRESS_H_
#define XDRIVER_MCU_TLV_PERIPHERAL_XHEADER_TLV_REGISTERADDRESS_H_

#include <xDriver_MCU/TLV/Peripheral/xHeader/TLV_Enum.h>

#define TLV_BASE    ((UBase_t) 0x01A0UL)
#define TLV_INFOBLOCK_BASE    ((UBase_t) 0x1A00UL)
#define TLV_DIERECORD_BASE    ((UBase_t) 0x1A08UL)
#define TLV_ADC12CAL_BASE    ((UBase_t) 0x1A14UL)
#define TLV_REFCAL_BASE    ((UBase_t) 0x01A26UL)
#define TLV_PD_BASE    ((UBase_t) 0x01A2EUL)


#define TLV_INFOBLOCK_INFOLENGTH_OFFSET    ((UBase_t) 0x0000UL)
#define TLV_INFOBLOCK_CRCLENGTH_OFFSET    ((UBase_t) 0x0001UL)
#define TLV_INFOBLOCK_CRCVALUE_OFFSET    ((UBase_t) 0x0002UL)
#define TLV_INFOBLOCK_DEVID0_OFFSET    ((UBase_t) 0x0004UL)
#define TLV_INFOBLOCK_DEVID1_OFFSET    ((UBase_t) 0x0005UL)
#define TLV_INFOBLOCK_HWREV_OFFSET    ((UBase_t) 0x0006UL)
#define TLV_INFOBLOCK_FWREV_OFFSET    ((UBase_t) 0x0007UL)


#define TLV_DIERECORD_TAG_OFFSET    ((UBase_t) 0x0000UL)
#define TLV_DIERECORD_LENGTH_OFFSET    ((UBase_t) 0x0001UL)
#define TLV_DIERECORD_WAFERID_OFFSET    ((UBase_t) 0x0002UL)
#define TLV_DIERECORD_DIEX_OFFSET    ((UBase_t) 0x0006UL)
#define TLV_DIERECORD_DIEY_OFFSET    ((UBase_t) 0x0008UL)
#define TLV_DIERECORD_TESTRESULTS_OFFSET    ((UBase_t) 0x000AUL)


#define TLV_ADC12CAL_TAG_OFFSET    ((UBase_t) 0x0000UL)
#define TLV_ADC12CAL_LENGTH_OFFSET    ((UBase_t) 0x0001UL)
#define TLV_ADC12CAL_GAINFACTOR_OFFSET    ((UBase_t) 0x0002UL)
#define TLV_ADC12CAL_OFFSET_OFFSET    ((UBase_t) 0x0004UL)
#define TLV_ADC12CAL_ADC1_5_30_OFFSET    ((UBase_t) 0x0006UL)
#define TLV_ADC12CAL_ADC1_5_85_OFFSET    ((UBase_t) 0x0008UL)
#define TLV_ADC12CAL_ADC2_0_30_OFFSET    ((UBase_t) 0x000AUL)
#define TLV_ADC12CAL_ADC2_0_85_OFFSET    ((UBase_t) 0x000CUL)
#define TLV_ADC12CAL_ADC2_5_30_OFFSET    ((UBase_t) 0x000EUL)
#define TLV_ADC12CAL_ADC2_5_85_OFFSET    ((UBase_t) 0x0010UL)


#define TLV_REFCAL_TAG_OFFSET    ((UBase_t) 0x0000UL)
#define TLV_REFCAL_LENGTH_OFFSET    ((UBase_t) 0x0001UL)
#define TLV_REFCAL_REF1_5_OFFSET    ((UBase_t) 0x0002UL)
#define TLV_REFCAL_REF2_0_OFFSET    ((UBase_t) 0x0004UL)
#define TLV_REFCAL_REF2_5_OFFSET    ((UBase_t) 0x0006UL)



#define TLV_INFOLENGTH_OFFSET    ((UBase_t) TLV_INFOBLOCK_BASE + TLV_INFOBLOCK_INFOLENGTH_OFFSET)
#define TLV_CRCLENGTH_OFFSET    ((UBase_t) TLV_INFOBLOCK_BASE + TLV_INFOBLOCK_CRCLENGTH_OFFSET)
#define TLV_CRCVALUE_OFFSET    ((UBase_t) TLV_INFOBLOCK_BASE + TLV_INFOBLOCK_CRCVALUE_OFFSET)
#define TLV_DEVID0_OFFSET    ((UBase_t) TLV_INFOBLOCK_BASE + TLV_INFOBLOCK_DEVID0_OFFSET)
#define TLV_DEVID1_OFFSET    ((UBase_t) TLV_INFOBLOCK_BASE + TLV_INFOBLOCK_DEVID1_OFFSET)
#define TLV_HWREV_OFFSET    ((UBase_t) TLV_INFOBLOCK_BASE + TLV_INFOBLOCK_HWREV_OFFSET)
#define TLV_FWREV_OFFSET    ((UBase_t) TLV_INFOBLOCK_BASE + TLV_INFOBLOCK_FWREV_OFFSET)

#define TLV_DIERECORDTAG_OFFSET    ((UBase_t) TLV_DIERECORD_BASE + TLV_DIERECORD_TAG_OFFSET)
#define TLV_DIERECORDLENGTH_OFFSET    ((UBase_t) TLV_DIERECORD_BASE + TLV_DIERECORD_LENGTH_OFFSET)
#define TLV_WAFERID_OFFSET    ((UBase_t) TLV_DIERECORD_BASE + TLV_DIERECORD_WAFERID_OFFSET)
#define TLV_DIEX_OFFSET    ((UBase_t) TLV_DIERECORD_BASE + TLV_DIERECORD_DIEX_OFFSET)
#define TLV_DIEY_OFFSET    ((UBase_t) TLV_DIERECORD_BASE + TLV_DIERECORD_DIEY_OFFSET)
#define TLV_TESTRESULTS_OFFSET    ((UBase_t) TLV_DIERECORD_BASE + TLV_DIERECORD_TESTRESULTS_OFFSET)

#define TLV_ADC12CALTAG_OFFSET    ((UBase_t) TLV_ADC12CAL_BASE + TLV_ADC12CAL_TAG_OFFSET)
#define TLV_ADC12CALLENGTH_OFFSET    ((UBase_t) TLV_ADC12CAL_BASE + TLV_ADC12CAL_LENGTH_OFFSET)
#define TLV_ADC12GAINFACTOR_OFFSET    ((UBase_t) TLV_ADC12CAL_BASE + TLV_ADC12CAL_GAINFACTOR_OFFSET)
#define TLV_ADC12OFFSET_OFFSET    ((UBase_t) TLV_ADC12CAL_BASE + TLV_ADC12CAL_OFFSET_OFFSET)
#define TLV_ADC12CAL1_5_30_OFFSET    ((UBase_t) TLV_ADC12CAL_BASE + TLV_ADC12CAL_ADC1_5_30_OFFSET)
#define TLV_ADC12CAL1_5_85_OFFSET    ((UBase_t) TLV_ADC12CAL_BASE + TLV_ADC12CAL_ADC1_5_85_OFFSET)
#define TLV_ADC12CAL2_0_30_OFFSET    ((UBase_t) TLV_ADC12CAL_BASE + TLV_ADC12CAL_ADC2_0_30_OFFSET)
#define TLV_ADC12CAL2_0_85_OFFSET    ((UBase_t) TLV_ADC12CAL_BASE + TLV_ADC12CAL_ADC2_0_85_OFFSET)
#define TLV_ADC12CAL2_5_30_OFFSET    ((UBase_t) TLV_ADC12CAL_BASE + TLV_ADC12CAL_ADC2_5_30_OFFSET)
#define TLV_ADC12CAL2_5_85_OFFSET    ((UBase_t) TLV_ADC12CAL_BASE + TLV_ADC12CAL_ADC2_5_85_OFFSET)

#define TLV_REFCALTAG_OFFSET    ((UBase_t) TLV_REFCAL_BASE + TLV_REFCAL_TAG_OFFSET)
#define TLV_REFCALLENGTH_OFFSET    ((UBase_t) TLV_REFCAL_BASE + TLV_REFCAL_LENGTH_OFFSET)
#define TLV_REFCAL1_5_OFFSET    ((UBase_t) TLV_REFCAL_BASE + TLV_REFCAL_REF1_5_OFFSET)
#define TLV_REFCAL2_0_OFFSET    ((UBase_t) TLV_REFCAL_BASE + TLV_REFCAL_REF2_0_OFFSET)
#define TLV_REFCAL2_5_OFFSET    ((UBase_t) TLV_REFCAL_BASE + TLV_REFCAL_REF2_5_OFFSET)


#endif /* XDRIVER_MCU_TLV_PERIPHERAL_XHEADER_TLV_REGISTERADDRESS_H_ */
