/**
 *
 * @file TIMERA_RegisterDefines_CC_CTL.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 9 abr. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 9 abr. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_TIMERA_PERIPHERAL_REGISTERDEFINES_HEADER_TIMERA_REGISTERDEFINES_CC_CTL_H_
#define DRIVERLIB_TIMERA_PERIPHERAL_REGISTERDEFINES_HEADER_TIMERA_REGISTERDEFINES_CC_CTL_H_

#include <xDriver_MCU/TIMERA/Peripheral/xHeader/TIMERA_Enum.h>

/******************************************************************************************
 ************************************ 3 CC_CTL *********************************************
 ******************************************************************************************/
/*-----------*/
#define TIMERA_CC_CTL_R_IFG_BIT ((UBase_t) 0U)

#define TIMERA_CC_CTL_IFG_MASK ((UBase_t) 0x01U)
#define TIMERA_CC_CTL_IFG_NOOCCUR ((UBase_t) 0x00U)
#define TIMERA_CC_CTL_IFG_OCCUR ((UBase_t) 0x01U)

#define TIMERA_CC_CTL_R_IFG_MASK (TIMERA_CC_CTL_IFG_MASK << TIMERA_CC_CTL_R_IFG_BIT)
#define TIMERA_CC_CTL_R_IFG_NOOCCUR (TIMERA_CC_CTL_IFG_NOOCCUR << TIMERA_CC_CTL_R_IFG_BIT)
#define TIMERA_CC_CTL_R_IFG_OCCUR (TIMERA_CC_CTL_IFG_OCCUR << TIMERA_CC_CTL_R_IFG_BIT)
/*-----------*/

/*-----------*/
#define TIMERA_CC_CTL_R_COV_BIT ((UBase_t) 1U)

#define TIMERA_CC_CTL_COV_MASK ((UBase_t) 0x01U)
#define TIMERA_CC_CTL_COV_NOOCCUR ((UBase_t) 0x00U)
#define TIMERA_CC_CTL_COV_OCCUR ((UBase_t) 0x01U)

#define TIMERA_CC_CTL_R_COV_MASK (TIMERA_CC_CTL_COV_MASK << TIMERA_CC_CTL_R_COV_BIT)
#define TIMERA_CC_CTL_R_COV_NOOCCUR (TIMERA_CC_CTL_COV_NOOCCUR << TIMERA_CC_CTL_R_COV_BIT)
#define TIMERA_CC_CTL_R_COV_OCCUR (TIMERA_CC_CTL_COV_OCCUR << TIMERA_CC_CTL_R_COV_BIT)
/*-----------*/

/*-----------*/
#define TIMERA_CC_CTL_R_OUT_BIT ((UBase_t) 2U)

#define TIMERA_CC_CTL_OUT_MASK ((UBase_t) 0x01U)
#define TIMERA_CC_CTL_OUT_LOW ((UBase_t) 0x00U)
#define TIMERA_CC_CTL_OUT_HIGH ((UBase_t) 0x01U)

#define TIMERA_CC_CTL_R_OUT_MASK (TIMERA_CC_CTL_OUT_MASK << TIMERA_CC_CTL_R_OUT_BIT)
#define TIMERA_CC_CTL_R_OUT_LOW (TIMERA_CC_CTL_OUT_LOW << TIMERA_CC_CTL_R_OUT_BIT)
#define TIMERA_CC_CTL_R_OUT_HIGH (TIMERA_CC_CTL_OUT_HIGH << TIMERA_CC_CTL_R_OUT_BIT)
/*-----------*/

/*-----------*/
#define TIMERA_CC_CTL_R_CCI_BIT ((UBase_t) 3U)

#define TIMERA_CC_CTL_CCI_MASK ((UBase_t) 0x01U)
#define TIMERA_CC_CTL_CCI_LOW ((UBase_t) 0x00U)
#define TIMERA_CC_CTL_CCI_HIGH ((UBase_t) 0x01U)

#define TIMERA_CC_CTL_R_CCI_MASK (TIMERA_CC_CTL_CCI_MASK << TIMERA_CC_CTL_R_CCI_BIT)
#define TIMERA_CC_CTL_R_CCI_LOW (TIMERA_CC_CTL_CCI_LOW << TIMERA_CC_CTL_R_CCI_BIT)
#define TIMERA_CC_CTL_R_CCI_HIGH (TIMERA_CC_CTL_CCI_HIGH << TIMERA_CC_CTL_R_CCI_BIT)
/*-----------*/

/*-----------*/
#define TIMERA_CC_CTL_R_IE_BIT ((UBase_t) 4U)

#define TIMERA_CC_CTL_IE_MASK ((UBase_t) 0x01U)
#define TIMERA_CC_CTL_IE_DIS ((UBase_t) 0x00U)
#define TIMERA_CC_CTL_IE_ENA ((UBase_t) 0x01U)

#define TIMERA_CC_CTL_R_IE_MASK (TIMERA_CC_CTL_IE_MASK << TIMERA_CC_CTL_R_IE_BIT)
#define TIMERA_CC_CTL_R_IE_DIS (TIMERA_CC_CTL_IE_DIS << TIMERA_CC_CTL_R_IE_BIT)
#define TIMERA_CC_CTL_R_IE_ENA (TIMERA_CC_CTL_IE_ENA << TIMERA_CC_CTL_R_IE_BIT)
/*-----------*/

/*-----------*/
#define TIMERA_CC_CTL_R_OUTMOD_BIT ((UBase_t) 5U)

#define TIMERA_CC_CTL_OUTMOD_MASK ((UBase_t) 0x07U)
#define TIMERA_CC_CTL_OUTMOD_OUT ((UBase_t) 0x00U)
#define TIMERA_CC_CTL_OUTMOD_SET ((UBase_t) 0x01U)
#define TIMERA_CC_CTL_OUTMOD_TOGGLE_RESET ((UBase_t) 0x02U)
#define TIMERA_CC_CTL_OUTMOD_SET_RESET ((UBase_t) 0x03U)
#define TIMERA_CC_CTL_OUTMOD_TOGGLE ((UBase_t) 0x04U)
#define TIMERA_CC_CTL_OUTMOD_RESET ((UBase_t) 0x05U)
#define TIMERA_CC_CTL_OUTMOD_TOGGLE_SET ((UBase_t) 0x06U)
#define TIMERA_CC_CTL_OUTMOD_RESET_SET ((UBase_t) 0x07U)

#define TIMERA_CC_CTL_R_OUTMOD_MASK (TIMERA_CC_CTL_OUTMOD_MASK << TIMERA_CC_CTL_R_OUTMOD_BIT)
#define TIMERA_CC_CTL_R_OUTMOD_OUT (TIMERA_CC_CTL_OUTMOD_OUT << TIMERA_CC_CTL_R_OUTMOD_BIT)
#define TIMERA_CC_CTL_R_OUTMOD_SET (TIMERA_CC_CTL_OUTMOD_SET << TIMERA_CC_CTL_R_OUTMOD_BIT)
#define TIMERA_CC_CTL_R_OUTMOD_TOGGLE_RESET (TIMERA_CC_CTL_OUTMOD_TOGGLE_RESET << TIMERA_CC_CTL_R_OUTMOD_BIT)
#define TIMERA_CC_CTL_R_OUTMOD_SET_RESET (TIMERA_CC_CTL_OUTMOD_SET_RESET << TIMERA_CC_CTL_R_OUTMOD_BIT)
#define TIMERA_CC_CTL_R_OUTMOD_TOGGLE (TIMERA_CC_CTL_OUTMOD_TOGGLE << TIMERA_CC_CTL_R_OUTMOD_BIT)
#define TIMERA_CC_CTL_R_OUTMOD_RESET (TIMERA_CC_CTL_OUTMOD_RESET << TIMERA_CC_CTL_R_OUTMOD_BIT)
#define TIMERA_CC_CTL_R_OUTMOD_TOGGLE_SET (TIMERA_CC_CTL_OUTMOD_TOGGLE_SET << TIMERA_CC_CTL_R_OUTMOD_BIT)
#define TIMERA_CC_CTL_R_OUTMOD_RESET_SET (TIMERA_CC_CTL_OUTMOD_RESET_SET << TIMERA_CC_CTL_R_OUTMOD_BIT)
/*-----------*/

/*-----------*/
#define TIMERA_CC_CTL_R_CAP_BIT ((UBase_t) 8U)

#define TIMERA_CC_CTL_CAP_MASK ((UBase_t) 0x01U)
#define TIMERA_CC_CTL_CAP_COMPARE ((UBase_t) 0x00U)
#define TIMERA_CC_CTL_CAP_CAPTURE ((UBase_t) 0x01U)

#define TIMERA_CC_CTL_R_CAP_MASK (TIMERA_CC_CTL_CAP_MASK << TIMERA_CC_CTL_R_CAP_BIT)
#define TIMERA_CC_CTL_R_CAP_COMPARE (TIMERA_CC_CTL_CAP_COMPARE << TIMERA_CC_CTL_R_CAP_BIT)
#define TIMERA_CC_CTL_R_CAP_CAPTURE (TIMERA_CC_CTL_CAP_CAPTURE << TIMERA_CC_CTL_R_CAP_BIT)
/*-----------*/

/*-----------*/
#define TIMERA_CC_CTL_R_SCCI_BIT ((UBase_t) 10U)

#define TIMERA_CC_CTL_SCCI_MASK ((UBase_t) 0x01U)
#define TIMERA_CC_CTL_SCCI_LOW ((UBase_t) 0x00U)
#define TIMERA_CC_CTL_SCCI_HIGH ((UBase_t) 0x01U)

#define TIMERA_CC_CTL_R_SCCI_MASK (TIMERA_CC_CTL_SCCI_MASK << TIMERA_CC_CTL_R_SCCI_BIT)
#define TIMERA_CC_CTL_R_SCCI_LOW (TIMERA_CC_CTL_SCCI_LOW << TIMERA_CC_CTL_R_SCCI_BIT)
#define TIMERA_CC_CTL_R_SCCI_HIGH (TIMERA_CC_CTL_SCCI_HIGH << TIMERA_CC_CTL_R_SCCI_BIT)
/*-----------*/

/*-----------*/
#define TIMERA_CC_CTL_R_SCS_BIT ((UBase_t) 11U)

#define TIMERA_CC_CTL_SCS_MASK ((UBase_t) 0x01U)
#define TIMERA_CC_CTL_SCS_ASYNC ((UBase_t) 0x00U)
#define TIMERA_CC_CTL_SCS_SYNC ((UBase_t) 0x01U)

#define TIMERA_CC_CTL_R_SCS_MASK (TIMERA_CC_CTL_SCS_MASK << TIMERA_CC_CTL_R_SCS_BIT)
#define TIMERA_CC_CTL_R_SCS_ASYNC (TIMERA_CC_CTL_SCS_ASYNC << TIMERA_CC_CTL_R_SCS_BIT)
#define TIMERA_CC_CTL_R_SCS_SYNC (TIMERA_CC_CTL_SCS_SYNC << TIMERA_CC_CTL_R_SCS_BIT)
/*-----------*/

/*-----------*/
#define TIMERA_CC_CTL_R_CCIS_BIT ((UBase_t) 12U)

#define TIMERA_CC_CTL_CCIS_MASK ((UBase_t) 0x03U)
#define TIMERA_CC_CTL_CCIS_CCIA ((UBase_t) 0x00U)
#define TIMERA_CC_CTL_CCIS_CCIB ((UBase_t) 0x01U)
#define TIMERA_CC_CTL_CCIS_GND ((UBase_t) 0x02U)
#define TIMERA_CC_CTL_CCIS_VCC ((UBase_t) 0x03U)

#define TIMERA_CC_CTL_R_CCIS_MASK (TIMERA_CC_CTL_CCIS_MASK << TIMERA_CC_CTL_R_CCIS_BIT)
#define TIMERA_CC_CTL_R_CCIS_CCIA (TIMERA_CC_CTL_CCIS_CCIA << TIMERA_CC_CTL_R_CCIS_BIT)
#define TIMERA_CC_CTL_R_CCIS_CCIB (TIMERA_CC_CTL_CCIS_CCIB << TIMERA_CC_CTL_R_CCIS_BIT)
#define TIMERA_CC_CTL_R_CCIS_GND (TIMERA_CC_CTL_CCIS_GND << TIMERA_CC_CTL_R_CCIS_BIT)
#define TIMERA_CC_CTL_R_CCIS_VCC (TIMERA_CC_CTL_CCIS_VCC << TIMERA_CC_CTL_R_CCIS_BIT)
/*-----------*/

/*-----------*/
#define TIMERA_CC_CTL_R_CM_BIT ((UBase_t) 14U)

#define TIMERA_CC_CTL_CM_MASK ((UBase_t) 0x03U)
#define TIMERA_CC_CTL_CM_NONE ((UBase_t) 0x00U)
#define TIMERA_CC_CTL_CM_RISING ((UBase_t) 0x01U)
#define TIMERA_CC_CTL_CM_FALLING ((UBase_t) 0x02U)
#define TIMERA_CC_CTL_CM_BOTH ((UBase_t) 0x03U)

#define TIMERA_CC_CTL_R_CM_MASK (TIMERA_CC_CTL_CM_MASK << TIMERA_CC_CTL_R_CM_BIT)
#define TIMERA_CC_CTL_R_CM_NONE (TIMERA_CC_CTL_CM_NONE << TIMERA_CC_CTL_R_CM_BIT)
#define TIMERA_CC_CTL_R_CM_RISING (TIMERA_CC_CTL_CM_RISING << TIMERA_CC_CTL_R_CM_BIT)
#define TIMERA_CC_CTL_R_CM_FALLING (TIMERA_CC_CTL_CM_FALLING << TIMERA_CC_CTL_R_CM_BIT)
#define TIMERA_CC_CTL_R_CM_BOTH (TIMERA_CC_CTL_CM_BOTH << TIMERA_CC_CTL_R_CM_BIT)
/*-----------*/

#endif /* DRIVERLIB_TIMERA_PERIPHERAL_REGISTERDEFINES_HEADER_TIMERA_REGISTERDEFINES_CC_CTL_H_ */
