/**
 *
 * @file DMA_RegisterDefines_CTL0.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 6 feb. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 6 feb. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DMA_PERIPHERAL_REGISTERDEFINES_HEADER_DMA_REGISTERDEFINES_CTL0_H_
#define DMA_PERIPHERAL_REGISTERDEFINES_HEADER_DMA_REGISTERDEFINES_CTL0_H_

#include <xDriver_MCU/DMA/Peripheral/xHeader/DMA_Enum.h>

/******************************************************************************************
 ************************************ 1 CTL0 *********************************************
 ******************************************************************************************/

#define DMA_CTL0_CHTSEL_MASK ((UBase_t) 0x1FU)
#define DMA_CTL0_CHTSEL_SW ((UBase_t) 0U)
#define DMA_CTL0_CHTSEL_TA0CCR0 ((UBase_t) 1U)
#define DMA_CTL0_CHTSEL_TA0CCR2 ((UBase_t) 2U)
#define DMA_CTL0_CHTSEL_TA2CCR0 ((UBase_t) 3U)
#define DMA_CTL0_CHTSEL_TA2CCR2 ((UBase_t) 4U)
#define DMA_CTL0_CHTSEL_UCA0_RX ((UBase_t) 16U)
#define DMA_CTL0_CHTSEL_UCA0_TX ((UBase_t) 17U)
#define DMA_CTL0_CHTSEL_UCB0_RX ((UBase_t) 18U)
#define DMA_CTL0_CHTSEL_UCB0_TX ((UBase_t) 19U)
#define DMA_CTL0_CHTSEL_ADC12x ((UBase_t) 24U)
#define DMA_CTL0_CHTSEL_MPY ((UBase_t) 29U)
#define DMA_CTL0_CHTSEL_DMA ((UBase_t) 30U)
#define DMA_CTL0_CHTSEL_EXTERNAL ((UBase_t) 31U)

/*-----------*/
#define DMA_CTL0_R_CH0TSEL_BIT ((UBase_t) 0U)

#define DMA_CTL0_CH0TSEL_MASK ((UBase_t) 32U)
#define DMA_CTL0_CH0TSEL_SW ((UBase_t) 0U)
#define DMA_CTL0_CH0TSEL_TA0CCR0 ((UBase_t) 1U)
#define DMA_CTL0_CH0TSEL_TA0CCR2 ((UBase_t) 2U)
#define DMA_CTL0_CH0TSEL_TA2CCR0 ((UBase_t) 3U)
#define DMA_CTL0_CH0TSEL_TA2CCR2 ((UBase_t) 4U)
#define DMA_CTL0_CH0TSEL_UCA0_RX ((UBase_t) 16U)
#define DMA_CTL0_CH0TSEL_UCA0_TX ((UBase_t) 17U)
#define DMA_CTL0_CH0TSEL_UCB0_RX ((UBase_t) 18U)
#define DMA_CTL0_CH0TSEL_UCB0_TX ((UBase_t) 19U)
#define DMA_CTL0_CH0TSEL_ADC12x ((UBase_t) 24U)
#define DMA_CTL0_CH0TSEL_MPY ((UBase_t) 29U)
#define DMA_CTL0_CH0TSEL_DMA ((UBase_t) 30U)
#define DMA_CTL0_CH0TSEL_EXTERNAL ((UBase_t) 31U)

#define DMA_CTL0_R_CH0TSEL_MASK (DMA_CTL0_CH0TSEL_MASK << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_SW (DMA_CTL0_CH0TSEL_SW << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_TA0CCR0 (DMA_CTL0_CH0TSEL_TA0CCR0 << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_TA0CCR2 (DMA_CTL0_CH0TSEL_TA0CCR2 << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_TA2CCR0 (DMA_CTL0_CH0TSEL_TA2CCR0 << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_TA2CCR2 (DMA_CTL0_CH0TSEL_TA2CCR2 << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_UCA0_RX (DMA_CTL0_CH0TSEL_UCA0_RX << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_UCA0_TX (DMA_CTL0_CH0TSEL_UCA0_TX << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_UCB0_RX (DMA_CTL0_CH0TSEL_UCB0_RX << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_UCB0_TX (DMA_CTL0_CH0TSEL_UCB0_TX << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_ADC12x (DMA_CTL0_CH0TSEL_ADC12x << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_MPY (DMA_CTL0_CH0TSEL_MPY << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_DMA (DMA_CTL0_CH0TSEL_DMA << DMA_CTL0_R_CH0TSEL_BIT)
#define DMA_CTL0_R_CH0TSEL_EXTERNAL (DMA_CTL0_CH0TSEL_EXTERNAL << DMA_CTL0_R_CH0TSEL_BIT)
/*-----------*/

/*-----------*/
#define DMA_CTL0_R_CH1TSEL_BIT ((UBase_t) 8U)

#define DMA_CTL0_CH1TSEL_MASK ((UBase_t) 0x1FU)
#define DMA_CTL0_CH1TSEL_SW ((UBase_t) 0U)
#define DMA_CTL0_CH1TSEL_TA0CCR0 ((UBase_t) 1U)
#define DMA_CTL0_CH1TSEL_TA0CCR2 ((UBase_t) 2U)
#define DMA_CTL0_CH1TSEL_TA2CCR0 ((UBase_t) 3U)
#define DMA_CTL0_CH1TSEL_TA2CCR2 ((UBase_t) 4U)
#define DMA_CTL0_CH1TSEL_UCA0_RX ((UBase_t) 16U)
#define DMA_CTL0_CH1TSEL_UCA0_TX ((UBase_t) 17U)
#define DMA_CTL0_CH1TSEL_UCB0_RX ((UBase_t) 18U)
#define DMA_CTL0_CH1TSEL_UCB0_TX ((UBase_t) 19U)
#define DMA_CTL0_CH1TSEL_ADC12x ((UBase_t) 24U)
#define DMA_CTL0_CH1TSEL_MPY ((UBase_t) 29U)
#define DMA_CTL0_CH1TSEL_DMA ((UBase_t) 30U)
#define DMA_CTL0_CH1TSEL_EXTERNAL ((UBase_t) 31U)

#define DMA_CTL0_R_CH1TSEL_MASK (DMA_CTL0_CH1TSEL_MASK << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_SW (DMA_CTL0_CH1TSEL_SW << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_TA0CCR0 (DMA_CTL0_CH1TSEL_TA0CCR0 << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_TA0CCR2 (DMA_CTL0_CH1TSEL_TA0CCR2 << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_TA2CCR0 (DMA_CTL0_CH1TSEL_TA2CCR0 << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_TA2CCR2 (DMA_CTL0_CH1TSEL_TA2CCR2 << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_UCA0_RX (DMA_CTL0_CH1TSEL_UCA0_RX << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_UCA0_TX (DMA_CTL0_CH1TSEL_UCA0_TX << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_UCB0_RX (DMA_CTL0_CH1TSEL_UCB0_RX << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_UCB0_TX (DMA_CTL0_CH1TSEL_UCB0_TX << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_ADC12x (DMA_CTL0_CH1TSEL_ADC12x << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_MPY (DMA_CTL0_CH1TSEL_MPY << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_DMA (DMA_CTL0_CH1TSEL_DMA << DMA_CTL0_R_CH1TSEL_BIT)
#define DMA_CTL0_R_CH1TSEL_EXTERNAL (DMA_CTL0_CH1TSEL_EXTERNAL << DMA_CTL0_R_CH1TSEL_BIT)
/*-----------*/

#endif /* DMA_PERIPHERAL_REGISTERDEFINES_HEADER_DMA_REGISTERDEFINES_CTL0_H_ */
