/**
 *
 * @file DMA_RegisterDefines_TRIGGER.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 14 feb. 2023 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 14 feb. 2023     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_DMA_PERIPHERAL_REGISTERDEFINES_XHEADER_DMA_REGISTERDEFINES_TRIGGER_H_
#define XDRIVER_MCU_DMA_PERIPHERAL_REGISTERDEFINES_XHEADER_DMA_REGISTERDEFINES_TRIGGER_H_

#include <xDriver_MCU/DMA/Peripheral/xHeader/DMA_Enum.h>

/******************************************************************************************
 ************************************ 1 TRIGGER *********************************************
 ******************************************************************************************/

#define DMA_TRIGGER_R_TSEL_BIT ((uint8_t) 0U)

#define DMA_TRIGGER_TSEL_MASK ((uint8_t) 0x1FU)
#define DMA_TRIGGER_TSEL_SW ((uint8_t) 0U)
#define DMA_TRIGGER_TSEL_TA0CCR0 ((uint8_t) 1U)
#define DMA_TRIGGER_TSEL_TA0CCR2 ((uint8_t) 2U)
#define DMA_TRIGGER_TSEL_TA2CCR0 ((uint8_t) 3U)
#define DMA_TRIGGER_TSEL_TA2CCR2 ((uint8_t) 4U)
#define DMA_TRIGGER_TSEL_UCA0_RX ((uint8_t) 16U)
#define DMA_TRIGGER_TSEL_UCA0_TX ((uint8_t) 17U)
#define DMA_TRIGGER_TSEL_UCB0_RX ((uint8_t) 18U)
#define DMA_TRIGGER_TSEL_UCB0_TX ((uint8_t) 19U)
#define DMA_TRIGGER_TSEL_ADC12x ((uint8_t) 24U)
#define DMA_TRIGGER_TSEL_MPY ((uint8_t) 29U)
#define DMA_TRIGGER_TSEL_DMA ((uint8_t) 30U)
#define DMA_TRIGGER_TSEL_EXTERNAL ((uint8_t) 31U)

#define DMA_TRIGGER_R_TSEL_MASK (DMA_TRIGGER_TSEL_MASK << DMA_TRIGGER_R_TSEL_BIT)
#define DMA_TRIGGER_R_TSEL_SW (DMA_TRIGGER_TSEL_SW << DMA_TRIGGER_R_TSEL_BIT)
#define DMA_TRIGGER_R_TSEL_TA0CCR0 (DMA_TRIGGER_TSEL_TA0CCR0 << DMA_TRIGGER_R_TSEL_BIT)
#define DMA_TRIGGER_R_TSEL_TA0CCR2 (DMA_TRIGGER_TSEL_TA0CCR2 << DMA_TRIGGER_R_TSEL_BIT)
#define DMA_TRIGGER_R_TSEL_TA2CCR0 (DMA_TRIGGER_TSEL_TA2CCR0 << DMA_TRIGGER_R_TSEL_BIT)
#define DMA_TRIGGER_R_TSEL_TA2CCR2 (DMA_TRIGGER_TSEL_TA2CCR2 << DMA_TRIGGER_R_TSEL_BIT)
#define DMA_TRIGGER_R_TSEL_UCA0_RX (DMA_TRIGGER_TSEL_UCA0_RX << DMA_TRIGGER_R_TSEL_BIT)
#define DMA_TRIGGER_R_TSEL_UCA0_TX (DMA_TRIGGER_TSEL_UCA0_TX << DMA_TRIGGER_R_TSEL_BIT)
#define DMA_TRIGGER_R_TSEL_UCB0_RX (DMA_TRIGGER_TSEL_UCB0_RX << DMA_TRIGGER_R_TSEL_BIT)
#define DMA_TRIGGER_R_TSEL_UCB0_TX (DMA_TRIGGER_TSEL_UCB0_TX << DMA_TRIGGER_R_TSEL_BIT)
#define DMA_TRIGGER_R_TSEL_ADC12x (DMA_TRIGGER_TSEL_ADC12x << DMA_TRIGGER_R_TSEL_BIT)
#define DMA_TRIGGER_R_TSEL_MPY (DMA_TRIGGER_TSEL_MPY << DMA_TRIGGER_R_TSEL_BIT)
#define DMA_TRIGGER_R_TSEL_DMA (DMA_TRIGGER_TSEL_DMA << DMA_TRIGGER_R_TSEL_BIT)
#define DMA_TRIGGER_R_TSEL_EXTERNAL (DMA_TRIGGER_TSEL_EXTERNAL << DMA_TRIGGER_R_TSEL_BIT)

/*-----------*/
#define DMA_CH0_TRIGGER_R_TSEL_BIT ((uint8_t) 0U)

#define DMA_CH0_TRIGGER_TSEL_MASK ((uint8_t) 0x1FU)
#define DMA_CH0_TRIGGER_TSEL_SW ((uint8_t) 0U)
#define DMA_CH0_TRIGGER_TSEL_TA0CCR0 ((uint8_t) 1U)
#define DMA_CH0_TRIGGER_TSEL_TA0CCR2 ((uint8_t) 2U)
#define DMA_CH0_TRIGGER_TSEL_TA2CCR0 ((uint8_t) 3U)
#define DMA_CH0_TRIGGER_TSEL_TA2CCR2 ((uint8_t) 4U)
#define DMA_CH0_TRIGGER_TSEL_UCA0_RX ((uint8_t) 16U)
#define DMA_CH0_TRIGGER_TSEL_UCA0_TX ((uint8_t) 17U)
#define DMA_CH0_TRIGGER_TSEL_UCB0_RX ((uint8_t) 18U)
#define DMA_CH0_TRIGGER_TSEL_UCB0_TX ((uint8_t) 19U)
#define DMA_CH0_TRIGGER_TSEL_ADC12x ((uint8_t) 24U)
#define DMA_CH0_TRIGGER_TSEL_MPY ((uint8_t) 29U)
#define DMA_CH0_TRIGGER_TSEL_DMA ((uint8_t) 30U)
#define DMA_CH0_TRIGGER_TSEL_EXTERNAL ((uint8_t) 31U)

#define DMA_CH0_TRIGGER_R_TSEL_MASK (DMA_CH0_TRIGGER_TSEL_MASK << DMA_CH0_TRIGGER_R_TSEL_BIT)
#define DMA_CH0_TRIGGER_R_TSEL_SW (DMA_CH0_TRIGGER_TSEL_SW << DMA_CH0_TRIGGER_R_TSEL_BIT)
#define DMA_CH0_TRIGGER_R_TSEL_TA0CCR0 (DMA_CH0_TRIGGER_TSEL_TA0CCR0 << DMA_CH0_TRIGGER_R_TSEL_BIT)
#define DMA_CH0_TRIGGER_R_TSEL_TA0CCR2 (DMA_CH0_TRIGGER_TSEL_TA0CCR2 << DMA_CH0_TRIGGER_R_TSEL_BIT)
#define DMA_CH0_TRIGGER_R_TSEL_TA2CCR0 (DMA_CH0_TRIGGER_TSEL_TA2CCR0 << DMA_CH0_TRIGGER_R_TSEL_BIT)
#define DMA_CH0_TRIGGER_R_TSEL_TA2CCR2 (DMA_CH0_TRIGGER_TSEL_TA2CCR2 << DMA_CH0_TRIGGER_R_TSEL_BIT)
#define DMA_CH0_TRIGGER_R_TSEL_UCA0_RX (DMA_CH0_TRIGGER_TSEL_UCA0_RX << DMA_CH0_TRIGGER_R_TSEL_BIT)
#define DMA_CH0_TRIGGER_R_TSEL_UCA0_TX (DMA_CH0_TRIGGER_TSEL_UCA0_TX << DMA_CH0_TRIGGER_R_TSEL_BIT)
#define DMA_CH0_TRIGGER_R_TSEL_UCB0_RX (DMA_CH0_TRIGGER_TSEL_UCB0_RX << DMA_CH0_TRIGGER_R_TSEL_BIT)
#define DMA_CH0_TRIGGER_R_TSEL_UCB0_TX (DMA_CH0_TRIGGER_TSEL_UCB0_TX << DMA_CH0_TRIGGER_R_TSEL_BIT)
#define DMA_CH0_TRIGGER_R_TSEL_ADC12x (DMA_CH0_TRIGGER_TSEL_ADC12x << DMA_CH0_TRIGGER_R_TSEL_BIT)
#define DMA_CH0_TRIGGER_R_TSEL_MPY (DMA_CH0_TRIGGER_TSEL_MPY << DMA_CH0_TRIGGER_R_TSEL_BIT)
#define DMA_CH0_TRIGGER_R_TSEL_DMA (DMA_CH0_TRIGGER_TSEL_DMA << DMA_CH0_TRIGGER_R_TSEL_BIT)
#define DMA_CH0_TRIGGER_R_TSEL_EXTERNAL (DMA_CH0_TRIGGER_TSEL_EXTERNAL << DMA_CH0_TRIGGER_R_TSEL_BIT)
/*-----------*/

/*-----------*/
#define DMA_CH1_TRIGGER_R_TSEL_BIT ((uint8_t) 0U)

#define DMA_CH1_TRIGGER_TSEL_MASK ((uint8_t) 0x1FU)
#define DMA_CH1_TRIGGER_TSEL_SW ((uint8_t) 0U)
#define DMA_CH1_TRIGGER_TSEL_TA0CCR0 ((uint8_t) 1U)
#define DMA_CH1_TRIGGER_TSEL_TA0CCR2 ((uint8_t) 2U)
#define DMA_CH1_TRIGGER_TSEL_TA2CCR0 ((uint8_t) 3U)
#define DMA_CH1_TRIGGER_TSEL_TA2CCR2 ((uint8_t) 4U)
#define DMA_CH1_TRIGGER_TSEL_UCA0_RX ((uint8_t) 16U)
#define DMA_CH1_TRIGGER_TSEL_UCA0_TX ((uint8_t) 17U)
#define DMA_CH1_TRIGGER_TSEL_UCB0_RX ((uint8_t) 18U)
#define DMA_CH1_TRIGGER_TSEL_UCB0_TX ((uint8_t) 19U)
#define DMA_CH1_TRIGGER_TSEL_ADC12x ((uint8_t) 24U)
#define DMA_CH1_TRIGGER_TSEL_MPY ((uint8_t) 29U)
#define DMA_CH1_TRIGGER_TSEL_DMA ((uint8_t) 30U)
#define DMA_CH1_TRIGGER_TSEL_EXTERNAL ((uint8_t) 31U)

#define DMA_CH1_TRIGGER_R_TSEL_MASK (DMA_CH1_TRIGGER_TSEL_MASK << DMA_CH1_TRIGGER_R_TSEL_BIT)
#define DMA_CH1_TRIGGER_R_TSEL_SW (DMA_CH1_TRIGGER_TSEL_SW << DMA_CH1_TRIGGER_R_TSEL_BIT)
#define DMA_CH1_TRIGGER_R_TSEL_TA0CCR0 (DMA_CH1_TRIGGER_TSEL_TA0CCR0 << DMA_CH1_TRIGGER_R_TSEL_BIT)
#define DMA_CH1_TRIGGER_R_TSEL_TA0CCR2 (DMA_CH1_TRIGGER_TSEL_TA0CCR2 << DMA_CH1_TRIGGER_R_TSEL_BIT)
#define DMA_CH1_TRIGGER_R_TSEL_TA2CCR0 (DMA_CH1_TRIGGER_TSEL_TA2CCR0 << DMA_CH1_TRIGGER_R_TSEL_BIT)
#define DMA_CH1_TRIGGER_R_TSEL_TA2CCR2 (DMA_CH1_TRIGGER_TSEL_TA2CCR2 << DMA_CH1_TRIGGER_R_TSEL_BIT)
#define DMA_CH1_TRIGGER_R_TSEL_UCA0_RX (DMA_CH1_TRIGGER_TSEL_UCA0_RX << DMA_CH1_TRIGGER_R_TSEL_BIT)
#define DMA_CH1_TRIGGER_R_TSEL_UCA0_TX (DMA_CH1_TRIGGER_TSEL_UCA0_TX << DMA_CH1_TRIGGER_R_TSEL_BIT)
#define DMA_CH1_TRIGGER_R_TSEL_UCB0_RX (DMA_CH1_TRIGGER_TSEL_UCB0_RX << DMA_CH1_TRIGGER_R_TSEL_BIT)
#define DMA_CH1_TRIGGER_R_TSEL_UCB0_TX (DMA_CH1_TRIGGER_TSEL_UCB0_TX << DMA_CH1_TRIGGER_R_TSEL_BIT)
#define DMA_CH1_TRIGGER_R_TSEL_ADC12x (DMA_CH1_TRIGGER_TSEL_ADC12x << DMA_CH1_TRIGGER_R_TSEL_BIT)
#define DMA_CH1_TRIGGER_R_TSEL_MPY (DMA_CH1_TRIGGER_TSEL_MPY << DMA_CH1_TRIGGER_R_TSEL_BIT)
#define DMA_CH1_TRIGGER_R_TSEL_DMA (DMA_CH1_TRIGGER_TSEL_DMA << DMA_CH1_TRIGGER_R_TSEL_BIT)
#define DMA_CH1_TRIGGER_R_TSEL_EXTERNAL (DMA_CH1_TRIGGER_TSEL_EXTERNAL << DMA_CH1_TRIGGER_R_TSEL_BIT)
/*-----------*/

/*-----------*/
#define DMA_CH2_TRIGGER_R_TSEL_BIT ((uint8_t) 0U)

#define DMA_CH2_TRIGGER_TSEL_MASK ((uint8_t) 0x1FU)
#define DMA_CH2_TRIGGER_TSEL_SW ((uint8_t) 0U)
#define DMA_CH2_TRIGGER_TSEL_TA0CCR0 ((uint8_t) 1U)
#define DMA_CH2_TRIGGER_TSEL_TA0CCR2 ((uint8_t) 2U)
#define DMA_CH2_TRIGGER_TSEL_TA2CCR0 ((uint8_t) 3U)
#define DMA_CH2_TRIGGER_TSEL_TA2CCR2 ((uint8_t) 4U)
#define DMA_CH2_TRIGGER_TSEL_UCA0_RX ((uint8_t) 16U)
#define DMA_CH2_TRIGGER_TSEL_UCA0_TX ((uint8_t) 17U)
#define DMA_CH2_TRIGGER_TSEL_UCB0_RX ((uint8_t) 18U)
#define DMA_CH2_TRIGGER_TSEL_UCB0_TX ((uint8_t) 19U)
#define DMA_CH2_TRIGGER_TSEL_ADC12x ((uint8_t) 24U)
#define DMA_CH2_TRIGGER_TSEL_MPY ((uint8_t) 29U)
#define DMA_CH2_TRIGGER_TSEL_DMA ((uint8_t) 30U)
#define DMA_CH2_TRIGGER_TSEL_EXTERNAL ((uint8_t) 31U)

#define DMA_CH2_TRIGGER_R_TSEL_MASK (DMA_CH2_TRIGGER_TSEL_MASK << DMA_CH2_TRIGGER_R_TSEL_BIT)
#define DMA_CH2_TRIGGER_R_TSEL_SW (DMA_CH2_TRIGGER_TSEL_SW << DMA_CH2_TRIGGER_R_TSEL_BIT)
#define DMA_CH2_TRIGGER_R_TSEL_TA0CCR0 (DMA_CH2_TRIGGER_TSEL_TA0CCR0 << DMA_CH2_TRIGGER_R_TSEL_BIT)
#define DMA_CH2_TRIGGER_R_TSEL_TA0CCR2 (DMA_CH2_TRIGGER_TSEL_TA0CCR2 << DMA_CH2_TRIGGER_R_TSEL_BIT)
#define DMA_CH2_TRIGGER_R_TSEL_TA2CCR0 (DMA_CH2_TRIGGER_TSEL_TA2CCR0 << DMA_CH2_TRIGGER_R_TSEL_BIT)
#define DMA_CH2_TRIGGER_R_TSEL_TA2CCR2 (DMA_CH2_TRIGGER_TSEL_TA2CCR2 << DMA_CH2_TRIGGER_R_TSEL_BIT)
#define DMA_CH2_TRIGGER_R_TSEL_UCA0_RX (DMA_CH2_TRIGGER_TSEL_UCA0_RX << DMA_CH2_TRIGGER_R_TSEL_BIT)
#define DMA_CH2_TRIGGER_R_TSEL_UCA0_TX (DMA_CH2_TRIGGER_TSEL_UCA0_TX << DMA_CH2_TRIGGER_R_TSEL_BIT)
#define DMA_CH2_TRIGGER_R_TSEL_UCB0_RX (DMA_CH2_TRIGGER_TSEL_UCB0_RX << DMA_CH2_TRIGGER_R_TSEL_BIT)
#define DMA_CH2_TRIGGER_R_TSEL_UCB0_TX (DMA_CH2_TRIGGER_TSEL_UCB0_TX << DMA_CH2_TRIGGER_R_TSEL_BIT)
#define DMA_CH2_TRIGGER_R_TSEL_ADC12x (DMA_CH2_TRIGGER_TSEL_ADC12x << DMA_CH2_TRIGGER_R_TSEL_BIT)
#define DMA_CH2_TRIGGER_R_TSEL_MPY (DMA_CH2_TRIGGER_TSEL_MPY << DMA_CH2_TRIGGER_R_TSEL_BIT)
#define DMA_CH2_TRIGGER_R_TSEL_DMA (DMA_CH2_TRIGGER_TSEL_DMA << DMA_CH2_TRIGGER_R_TSEL_BIT)
#define DMA_CH2_TRIGGER_R_TSEL_EXTERNAL (DMA_CH2_TRIGGER_TSEL_EXTERNAL << DMA_CH2_TRIGGER_R_TSEL_BIT)
/*-----------*/

/*-----------*/
#define DMA_CH3_TRIGGER_R_TSEL_BIT ((uint8_t) 0U)

#define DMA_CH3_TRIGGER_TSEL_MASK ((uint8_t) 0x1FU)
#define DMA_CH3_TRIGGER_TSEL_SW ((uint8_t) 0U)
#define DMA_CH3_TRIGGER_TSEL_TA0CCR0 ((uint8_t) 1U)
#define DMA_CH3_TRIGGER_TSEL_TA0CCR2 ((uint8_t) 2U)
#define DMA_CH3_TRIGGER_TSEL_TA2CCR0 ((uint8_t) 3U)
#define DMA_CH3_TRIGGER_TSEL_TA2CCR2 ((uint8_t) 4U)
#define DMA_CH3_TRIGGER_TSEL_UCA0_RX ((uint8_t) 16U)
#define DMA_CH3_TRIGGER_TSEL_UCA0_TX ((uint8_t) 17U)
#define DMA_CH3_TRIGGER_TSEL_UCB0_RX ((uint8_t) 18U)
#define DMA_CH3_TRIGGER_TSEL_UCB0_TX ((uint8_t) 19U)
#define DMA_CH3_TRIGGER_TSEL_ADC12x ((uint8_t) 24U)
#define DMA_CH3_TRIGGER_TSEL_MPY ((uint8_t) 29U)
#define DMA_CH3_TRIGGER_TSEL_DMA ((uint8_t) 30U)
#define DMA_CH3_TRIGGER_TSEL_EXTERNAL ((uint8_t) 31U)

#define DMA_CH3_TRIGGER_R_TSEL_MASK (DMA_CH3_TRIGGER_TSEL_MASK << DMA_CH3_TRIGGER_R_TSEL_BIT)
#define DMA_CH3_TRIGGER_R_TSEL_SW (DMA_CH3_TRIGGER_TSEL_SW << DMA_CH3_TRIGGER_R_TSEL_BIT)
#define DMA_CH3_TRIGGER_R_TSEL_TA0CCR0 (DMA_CH3_TRIGGER_TSEL_TA0CCR0 << DMA_CH3_TRIGGER_R_TSEL_BIT)
#define DMA_CH3_TRIGGER_R_TSEL_TA0CCR2 (DMA_CH3_TRIGGER_TSEL_TA0CCR2 << DMA_CH3_TRIGGER_R_TSEL_BIT)
#define DMA_CH3_TRIGGER_R_TSEL_TA2CCR0 (DMA_CH3_TRIGGER_TSEL_TA2CCR0 << DMA_CH3_TRIGGER_R_TSEL_BIT)
#define DMA_CH3_TRIGGER_R_TSEL_TA2CCR2 (DMA_CH3_TRIGGER_TSEL_TA2CCR2 << DMA_CH3_TRIGGER_R_TSEL_BIT)
#define DMA_CH3_TRIGGER_R_TSEL_UCA0_RX (DMA_CH3_TRIGGER_TSEL_UCA0_RX << DMA_CH3_TRIGGER_R_TSEL_BIT)
#define DMA_CH3_TRIGGER_R_TSEL_UCA0_TX (DMA_CH3_TRIGGER_TSEL_UCA0_TX << DMA_CH3_TRIGGER_R_TSEL_BIT)
#define DMA_CH3_TRIGGER_R_TSEL_UCB0_RX (DMA_CH3_TRIGGER_TSEL_UCB0_RX << DMA_CH3_TRIGGER_R_TSEL_BIT)
#define DMA_CH3_TRIGGER_R_TSEL_UCB0_TX (DMA_CH3_TRIGGER_TSEL_UCB0_TX << DMA_CH3_TRIGGER_R_TSEL_BIT)
#define DMA_CH3_TRIGGER_R_TSEL_ADC12x (DMA_CH3_TRIGGER_TSEL_ADC12x << DMA_CH3_TRIGGER_R_TSEL_BIT)
#define DMA_CH3_TRIGGER_R_TSEL_MPY (DMA_CH3_TRIGGER_TSEL_MPY << DMA_CH3_TRIGGER_R_TSEL_BIT)
#define DMA_CH3_TRIGGER_R_TSEL_DMA (DMA_CH3_TRIGGER_TSEL_DMA << DMA_CH3_TRIGGER_R_TSEL_BIT)
#define DMA_CH3_TRIGGER_R_TSEL_EXTERNAL (DMA_CH3_TRIGGER_TSEL_EXTERNAL << DMA_CH3_TRIGGER_R_TSEL_BIT)
/*-----------*/

/*-----------*/
#define DMA_CH4_TRIGGER_R_TSEL_BIT ((uint8_t) 0U)

#define DMA_CH4_TRIGGER_TSEL_MASK ((uint8_t) 0x1FU)
#define DMA_CH4_TRIGGER_TSEL_SW ((uint8_t) 0U)
#define DMA_CH4_TRIGGER_TSEL_TA0CCR0 ((uint8_t) 1U)
#define DMA_CH4_TRIGGER_TSEL_TA0CCR2 ((uint8_t) 2U)
#define DMA_CH4_TRIGGER_TSEL_TA2CCR0 ((uint8_t) 3U)
#define DMA_CH4_TRIGGER_TSEL_TA2CCR2 ((uint8_t) 4U)
#define DMA_CH4_TRIGGER_TSEL_UCA0_RX ((uint8_t) 16U)
#define DMA_CH4_TRIGGER_TSEL_UCA0_TX ((uint8_t) 17U)
#define DMA_CH4_TRIGGER_TSEL_UCB0_RX ((uint8_t) 18U)
#define DMA_CH4_TRIGGER_TSEL_UCB0_TX ((uint8_t) 19U)
#define DMA_CH4_TRIGGER_TSEL_ADC12x ((uint8_t) 24U)
#define DMA_CH4_TRIGGER_TSEL_MPY ((uint8_t) 29U)
#define DMA_CH4_TRIGGER_TSEL_DMA ((uint8_t) 30U)
#define DMA_CH4_TRIGGER_TSEL_EXTERNAL ((uint8_t) 31U)

#define DMA_CH4_TRIGGER_R_TSEL_MASK (DMA_CH4_TRIGGER_TSEL_MASK << DMA_CH4_TRIGGER_R_TSEL_BIT)
#define DMA_CH4_TRIGGER_R_TSEL_SW (DMA_CH4_TRIGGER_TSEL_SW << DMA_CH4_TRIGGER_R_TSEL_BIT)
#define DMA_CH4_TRIGGER_R_TSEL_TA0CCR0 (DMA_CH4_TRIGGER_TSEL_TA0CCR0 << DMA_CH4_TRIGGER_R_TSEL_BIT)
#define DMA_CH4_TRIGGER_R_TSEL_TA0CCR2 (DMA_CH4_TRIGGER_TSEL_TA0CCR2 << DMA_CH4_TRIGGER_R_TSEL_BIT)
#define DMA_CH4_TRIGGER_R_TSEL_TA2CCR0 (DMA_CH4_TRIGGER_TSEL_TA2CCR0 << DMA_CH4_TRIGGER_R_TSEL_BIT)
#define DMA_CH4_TRIGGER_R_TSEL_TA2CCR2 (DMA_CH4_TRIGGER_TSEL_TA2CCR2 << DMA_CH4_TRIGGER_R_TSEL_BIT)
#define DMA_CH4_TRIGGER_R_TSEL_UCA0_RX (DMA_CH4_TRIGGER_TSEL_UCA0_RX << DMA_CH4_TRIGGER_R_TSEL_BIT)
#define DMA_CH4_TRIGGER_R_TSEL_UCA0_TX (DMA_CH4_TRIGGER_TSEL_UCA0_TX << DMA_CH4_TRIGGER_R_TSEL_BIT)
#define DMA_CH4_TRIGGER_R_TSEL_UCB0_RX (DMA_CH4_TRIGGER_TSEL_UCB0_RX << DMA_CH4_TRIGGER_R_TSEL_BIT)
#define DMA_CH4_TRIGGER_R_TSEL_UCB0_TX (DMA_CH4_TRIGGER_TSEL_UCB0_TX << DMA_CH4_TRIGGER_R_TSEL_BIT)
#define DMA_CH4_TRIGGER_R_TSEL_ADC12x (DMA_CH4_TRIGGER_TSEL_ADC12x << DMA_CH4_TRIGGER_R_TSEL_BIT)
#define DMA_CH4_TRIGGER_R_TSEL_MPY (DMA_CH4_TRIGGER_TSEL_MPY << DMA_CH4_TRIGGER_R_TSEL_BIT)
#define DMA_CH4_TRIGGER_R_TSEL_DMA (DMA_CH4_TRIGGER_TSEL_DMA << DMA_CH4_TRIGGER_R_TSEL_BIT)
#define DMA_CH4_TRIGGER_R_TSEL_EXTERNAL (DMA_CH4_TRIGGER_TSEL_EXTERNAL << DMA_CH4_TRIGGER_R_TSEL_BIT)
/*-----------*/


/*-----------*/
#define DMA_CH5_TRIGGER_R_TSEL_BIT ((uint8_t) 0U)

#define DMA_CH5_TRIGGER_TSEL_MASK ((uint8_t) 0x1FU)
#define DMA_CH5_TRIGGER_TSEL_SW ((uint8_t) 0U)
#define DMA_CH5_TRIGGER_TSEL_TA0CCR0 ((uint8_t) 1U)
#define DMA_CH5_TRIGGER_TSEL_TA0CCR2 ((uint8_t) 2U)
#define DMA_CH5_TRIGGER_TSEL_TA2CCR0 ((uint8_t) 3U)
#define DMA_CH5_TRIGGER_TSEL_TA2CCR2 ((uint8_t) 4U)
#define DMA_CH5_TRIGGER_TSEL_UCA0_RX ((uint8_t) 16U)
#define DMA_CH5_TRIGGER_TSEL_UCA0_TX ((uint8_t) 17U)
#define DMA_CH5_TRIGGER_TSEL_UCB0_RX ((uint8_t) 18U)
#define DMA_CH5_TRIGGER_TSEL_UCB0_TX ((uint8_t) 19U)
#define DMA_CH5_TRIGGER_TSEL_ADC12x ((uint8_t) 24U)
#define DMA_CH5_TRIGGER_TSEL_MPY ((uint8_t) 29U)
#define DMA_CH5_TRIGGER_TSEL_DMA ((uint8_t) 30U)
#define DMA_CH5_TRIGGER_TSEL_EXTERNAL ((uint8_t) 31U)

#define DMA_CH5_TRIGGER_R_TSEL_MASK (DMA_CH5_TRIGGER_TSEL_MASK << DMA_CH5_TRIGGER_R_TSEL_BIT)
#define DMA_CH5_TRIGGER_R_TSEL_SW (DMA_CH5_TRIGGER_TSEL_SW << DMA_CH5_TRIGGER_R_TSEL_BIT)
#define DMA_CH5_TRIGGER_R_TSEL_TA0CCR0 (DMA_CH5_TRIGGER_TSEL_TA0CCR0 << DMA_CH5_TRIGGER_R_TSEL_BIT)
#define DMA_CH5_TRIGGER_R_TSEL_TA0CCR2 (DMA_CH5_TRIGGER_TSEL_TA0CCR2 << DMA_CH5_TRIGGER_R_TSEL_BIT)
#define DMA_CH5_TRIGGER_R_TSEL_TA2CCR0 (DMA_CH5_TRIGGER_TSEL_TA2CCR0 << DMA_CH5_TRIGGER_R_TSEL_BIT)
#define DMA_CH5_TRIGGER_R_TSEL_TA2CCR2 (DMA_CH5_TRIGGER_TSEL_TA2CCR2 << DMA_CH5_TRIGGER_R_TSEL_BIT)
#define DMA_CH5_TRIGGER_R_TSEL_UCA0_RX (DMA_CH5_TRIGGER_TSEL_UCA0_RX << DMA_CH5_TRIGGER_R_TSEL_BIT)
#define DMA_CH5_TRIGGER_R_TSEL_UCA0_TX (DMA_CH5_TRIGGER_TSEL_UCA0_TX << DMA_CH5_TRIGGER_R_TSEL_BIT)
#define DMA_CH5_TRIGGER_R_TSEL_UCB0_RX (DMA_CH5_TRIGGER_TSEL_UCB0_RX << DMA_CH5_TRIGGER_R_TSEL_BIT)
#define DMA_CH5_TRIGGER_R_TSEL_UCB0_TX (DMA_CH5_TRIGGER_TSEL_UCB0_TX << DMA_CH5_TRIGGER_R_TSEL_BIT)
#define DMA_CH5_TRIGGER_R_TSEL_ADC12x (DMA_CH5_TRIGGER_TSEL_ADC12x << DMA_CH5_TRIGGER_R_TSEL_BIT)
#define DMA_CH5_TRIGGER_R_TSEL_MPY (DMA_CH5_TRIGGER_TSEL_MPY << DMA_CH5_TRIGGER_R_TSEL_BIT)
#define DMA_CH5_TRIGGER_R_TSEL_DMA (DMA_CH5_TRIGGER_TSEL_DMA << DMA_CH5_TRIGGER_R_TSEL_BIT)
#define DMA_CH5_TRIGGER_R_TSEL_EXTERNAL (DMA_CH5_TRIGGER_TSEL_EXTERNAL << DMA_CH5_TRIGGER_R_TSEL_BIT)
/*-----------*/


/*-----------*/
#define DMA_CH6_TRIGGER_R_TSEL_BIT ((uint8_t) 0U)

#define DMA_CH6_TRIGGER_TSEL_MASK ((uint8_t) 0x1FU)
#define DMA_CH6_TRIGGER_TSEL_SW ((uint8_t) 0U)
#define DMA_CH6_TRIGGER_TSEL_TA0CCR0 ((uint8_t) 1U)
#define DMA_CH6_TRIGGER_TSEL_TA0CCR2 ((uint8_t) 2U)
#define DMA_CH6_TRIGGER_TSEL_TA2CCR0 ((uint8_t) 3U)
#define DMA_CH6_TRIGGER_TSEL_TA2CCR2 ((uint8_t) 4U)
#define DMA_CH6_TRIGGER_TSEL_UCA0_RX ((uint8_t) 16U)
#define DMA_CH6_TRIGGER_TSEL_UCA0_TX ((uint8_t) 17U)
#define DMA_CH6_TRIGGER_TSEL_UCB0_RX ((uint8_t) 18U)
#define DMA_CH6_TRIGGER_TSEL_UCB0_TX ((uint8_t) 19U)
#define DMA_CH6_TRIGGER_TSEL_ADC12x ((uint8_t) 24U)
#define DMA_CH6_TRIGGER_TSEL_MPY ((uint8_t) 29U)
#define DMA_CH6_TRIGGER_TSEL_DMA ((uint8_t) 30U)
#define DMA_CH6_TRIGGER_TSEL_EXTERNAL ((uint8_t) 31U)

#define DMA_CH6_TRIGGER_R_TSEL_MASK (DMA_CH6_TRIGGER_TSEL_MASK << DMA_CH6_TRIGGER_R_TSEL_BIT)
#define DMA_CH6_TRIGGER_R_TSEL_SW (DMA_CH6_TRIGGER_TSEL_SW << DMA_CH6_TRIGGER_R_TSEL_BIT)
#define DMA_CH6_TRIGGER_R_TSEL_TA0CCR0 (DMA_CH6_TRIGGER_TSEL_TA0CCR0 << DMA_CH6_TRIGGER_R_TSEL_BIT)
#define DMA_CH6_TRIGGER_R_TSEL_TA0CCR2 (DMA_CH6_TRIGGER_TSEL_TA0CCR2 << DMA_CH6_TRIGGER_R_TSEL_BIT)
#define DMA_CH6_TRIGGER_R_TSEL_TA2CCR0 (DMA_CH6_TRIGGER_TSEL_TA2CCR0 << DMA_CH6_TRIGGER_R_TSEL_BIT)
#define DMA_CH6_TRIGGER_R_TSEL_TA2CCR2 (DMA_CH6_TRIGGER_TSEL_TA2CCR2 << DMA_CH6_TRIGGER_R_TSEL_BIT)
#define DMA_CH6_TRIGGER_R_TSEL_UCA0_RX (DMA_CH6_TRIGGER_TSEL_UCA0_RX << DMA_CH6_TRIGGER_R_TSEL_BIT)
#define DMA_CH6_TRIGGER_R_TSEL_UCA0_TX (DMA_CH6_TRIGGER_TSEL_UCA0_TX << DMA_CH6_TRIGGER_R_TSEL_BIT)
#define DMA_CH6_TRIGGER_R_TSEL_UCB0_RX (DMA_CH6_TRIGGER_TSEL_UCB0_RX << DMA_CH6_TRIGGER_R_TSEL_BIT)
#define DMA_CH6_TRIGGER_R_TSEL_UCB0_TX (DMA_CH6_TRIGGER_TSEL_UCB0_TX << DMA_CH6_TRIGGER_R_TSEL_BIT)
#define DMA_CH6_TRIGGER_R_TSEL_ADC12x (DMA_CH6_TRIGGER_TSEL_ADC12x << DMA_CH6_TRIGGER_R_TSEL_BIT)
#define DMA_CH6_TRIGGER_R_TSEL_MPY (DMA_CH6_TRIGGER_TSEL_MPY << DMA_CH6_TRIGGER_R_TSEL_BIT)
#define DMA_CH6_TRIGGER_R_TSEL_DMA (DMA_CH6_TRIGGER_TSEL_DMA << DMA_CH6_TRIGGER_R_TSEL_BIT)
#define DMA_CH6_TRIGGER_R_TSEL_EXTERNAL (DMA_CH6_TRIGGER_TSEL_EXTERNAL << DMA_CH6_TRIGGER_R_TSEL_BIT)
/*-----------*/


/*-----------*/
#define DMA_CH7_TRIGGER_R_TSEL_BIT ((uint8_t) 0U)

#define DMA_CH7_TRIGGER_TSEL_MASK ((uint8_t) 0x1FU)
#define DMA_CH7_TRIGGER_TSEL_SW ((uint8_t) 0U)
#define DMA_CH7_TRIGGER_TSEL_TA0CCR0 ((uint8_t) 1U)
#define DMA_CH7_TRIGGER_TSEL_TA0CCR2 ((uint8_t) 2U)
#define DMA_CH7_TRIGGER_TSEL_TA2CCR0 ((uint8_t) 3U)
#define DMA_CH7_TRIGGER_TSEL_TA2CCR2 ((uint8_t) 4U)
#define DMA_CH7_TRIGGER_TSEL_UCA0_RX ((uint8_t) 16U)
#define DMA_CH7_TRIGGER_TSEL_UCA0_TX ((uint8_t) 17U)
#define DMA_CH7_TRIGGER_TSEL_UCB0_RX ((uint8_t) 18U)
#define DMA_CH7_TRIGGER_TSEL_UCB0_TX ((uint8_t) 19U)
#define DMA_CH7_TRIGGER_TSEL_ADC12x ((uint8_t) 24U)
#define DMA_CH7_TRIGGER_TSEL_MPY ((uint8_t) 29U)
#define DMA_CH7_TRIGGER_TSEL_DMA ((uint8_t) 30U)
#define DMA_CH7_TRIGGER_TSEL_EXTERNAL ((uint8_t) 31U)

#define DMA_CH7_TRIGGER_R_TSEL_MASK (DMA_CH7_TRIGGER_TSEL_MASK << DMA_CH7_TRIGGER_R_TSEL_BIT)
#define DMA_CH7_TRIGGER_R_TSEL_SW (DMA_CH7_TRIGGER_TSEL_SW << DMA_CH7_TRIGGER_R_TSEL_BIT)
#define DMA_CH7_TRIGGER_R_TSEL_TA0CCR0 (DMA_CH7_TRIGGER_TSEL_TA0CCR0 << DMA_CH7_TRIGGER_R_TSEL_BIT)
#define DMA_CH7_TRIGGER_R_TSEL_TA0CCR2 (DMA_CH7_TRIGGER_TSEL_TA0CCR2 << DMA_CH7_TRIGGER_R_TSEL_BIT)
#define DMA_CH7_TRIGGER_R_TSEL_TA2CCR0 (DMA_CH7_TRIGGER_TSEL_TA2CCR0 << DMA_CH7_TRIGGER_R_TSEL_BIT)
#define DMA_CH7_TRIGGER_R_TSEL_TA2CCR2 (DMA_CH7_TRIGGER_TSEL_TA2CCR2 << DMA_CH7_TRIGGER_R_TSEL_BIT)
#define DMA_CH7_TRIGGER_R_TSEL_UCA0_RX (DMA_CH7_TRIGGER_TSEL_UCA0_RX << DMA_CH7_TRIGGER_R_TSEL_BIT)
#define DMA_CH7_TRIGGER_R_TSEL_UCA0_TX (DMA_CH7_TRIGGER_TSEL_UCA0_TX << DMA_CH7_TRIGGER_R_TSEL_BIT)
#define DMA_CH7_TRIGGER_R_TSEL_UCB0_RX (DMA_CH7_TRIGGER_TSEL_UCB0_RX << DMA_CH7_TRIGGER_R_TSEL_BIT)
#define DMA_CH7_TRIGGER_R_TSEL_UCB0_TX (DMA_CH7_TRIGGER_TSEL_UCB0_TX << DMA_CH7_TRIGGER_R_TSEL_BIT)
#define DMA_CH7_TRIGGER_R_TSEL_ADC12x (DMA_CH7_TRIGGER_TSEL_ADC12x << DMA_CH7_TRIGGER_R_TSEL_BIT)
#define DMA_CH7_TRIGGER_R_TSEL_MPY (DMA_CH7_TRIGGER_TSEL_MPY << DMA_CH7_TRIGGER_R_TSEL_BIT)
#define DMA_CH7_TRIGGER_R_TSEL_DMA (DMA_CH7_TRIGGER_TSEL_DMA << DMA_CH7_TRIGGER_R_TSEL_BIT)
#define DMA_CH7_TRIGGER_R_TSEL_EXTERNAL (DMA_CH7_TRIGGER_TSEL_EXTERNAL << DMA_CH7_TRIGGER_R_TSEL_BIT)
/*-----------*/
#endif /* XDRIVER_MCU_DMA_PERIPHERAL_REGISTERDEFINES_XHEADER_DMA_REGISTERDEFINES_TRIGGER_H_ */
