/**
 *
 * @file DMA_RegisterDefines_CTL2.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 14 feb. 2023 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 14 feb. 2023     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_DMA_PERIPHERAL_REGISTERDEFINES_XHEADER_DMA_REGISTERDEFINES_CTL2_H_
#define XDRIVER_MCU_DMA_PERIPHERAL_REGISTERDEFINES_XHEADER_DMA_REGISTERDEFINES_CTL2_H_

#include <xDriver_MCU/DMA/Peripheral/xHeader/DMA_Enum.h>

/******************************************************************************************
 ************************************ 1 CTL2 *********************************************
 ******************************************************************************************/

#define DMA_CTL2_CHTSEL_MASK ((UBase_t) 0x1FU)
#define DMA_CTL2_CHTSEL_SW ((UBase_t) 0U)
#define DMA_CTL2_CHTSEL_TA0CCR0 ((UBase_t) 1U)
#define DMA_CTL2_CHTSEL_TA0CCR2 ((UBase_t) 2U)
#define DMA_CTL2_CHTSEL_TA2CCR0 ((UBase_t) 3U)
#define DMA_CTL2_CHTSEL_TA2CCR2 ((UBase_t) 4U)
#define DMA_CTL2_CHTSEL_UCA0_RX ((UBase_t) 16U)
#define DMA_CTL2_CHTSEL_UCA0_TX ((UBase_t) 17U)
#define DMA_CTL2_CHTSEL_UCB0_RX ((UBase_t) 18U)
#define DMA_CTL2_CHTSEL_UCB0_TX ((UBase_t) 19U)
#define DMA_CTL2_CHTSEL_ADC12x ((UBase_t) 24U)
#define DMA_CTL2_CHTSEL_MPY ((UBase_t) 29U)
#define DMA_CTL2_CHTSEL_DMA ((UBase_t) 30U)
#define DMA_CTL2_CHTSEL_EXTERNAL ((UBase_t) 31U)

/*-----------*/
#define DMA_CTL2_R_CH4TSEL_BIT ((UBase_t) 0U)

#define DMA_CTL2_CH4TSEL_MASK ((UBase_t) 32U)
#define DMA_CTL2_CH4TSEL_SW ((UBase_t) 0U)
#define DMA_CTL2_CH4TSEL_TA0CCR0 ((UBase_t) 1U)
#define DMA_CTL2_CH4TSEL_TA0CCR2 ((UBase_t) 2U)
#define DMA_CTL2_CH4TSEL_TA2CCR0 ((UBase_t) 3U)
#define DMA_CTL2_CH4TSEL_TA2CCR2 ((UBase_t) 4U)
#define DMA_CTL2_CH4TSEL_UCA0_RX ((UBase_t) 16U)
#define DMA_CTL2_CH4TSEL_UCA0_TX ((UBase_t) 17U)
#define DMA_CTL2_CH4TSEL_UCB0_RX ((UBase_t) 18U)
#define DMA_CTL2_CH4TSEL_UCB0_TX ((UBase_t) 19U)
#define DMA_CTL2_CH4TSEL_ADC12x ((UBase_t) 24U)
#define DMA_CTL2_CH4TSEL_MPY ((UBase_t) 29U)
#define DMA_CTL2_CH4TSEL_DMA ((UBase_t) 30U)
#define DMA_CTL2_CH4TSEL_EXTERNAL ((UBase_t) 31U)

#define DMA_CTL2_R_CH4TSEL_MASK (DMA_CTL2_CH4TSEL_MASK << DMA_CTL2_R_CH4TSEL_BIT)
#define DMA_CTL2_R_CH4TSEL_SW (DMA_CTL2_CH4TSEL_SW << DMA_CTL2_R_CH4TSEL_BIT)
#define DMA_CTL2_R_CH4TSEL_TA0CCR0 (DMA_CTL2_CH4TSEL_TA0CCR0 << DMA_CTL2_R_CH4TSEL_BIT)
#define DMA_CTL2_R_CH4TSEL_TA0CCR2 (DMA_CTL2_CH4TSEL_TA0CCR2 << DMA_CTL2_R_CH4TSEL_BIT)
#define DMA_CTL2_R_CH4TSEL_TA2CCR0 (DMA_CTL2_CH4TSEL_TA2CCR0 << DMA_CTL2_R_CH4TSEL_BIT)
#define DMA_CTL2_R_CH4TSEL_TA2CCR2 (DMA_CTL2_CH4TSEL_TA2CCR2 << DMA_CTL2_R_CH4TSEL_BIT)
#define DMA_CTL2_R_CH4TSEL_UCA0_RX (DMA_CTL2_CH4TSEL_UCA0_RX << DMA_CTL2_R_CH4TSEL_BIT)
#define DMA_CTL2_R_CH4TSEL_UCA0_TX (DMA_CTL2_CH4TSEL_UCA0_TX << DMA_CTL2_R_CH4TSEL_BIT)
#define DMA_CTL2_R_CH4TSEL_UCB0_RX (DMA_CTL2_CH4TSEL_UCB0_RX << DMA_CTL2_R_CH4TSEL_BIT)
#define DMA_CTL2_R_CH4TSEL_UCB0_TX (DMA_CTL2_CH4TSEL_UCB0_TX << DMA_CTL2_R_CH4TSEL_BIT)
#define DMA_CTL2_R_CH4TSEL_ADC12x (DMA_CTL2_CH4TSEL_ADC12x << DMA_CTL2_R_CH4TSEL_BIT)
#define DMA_CTL2_R_CH4TSEL_MPY (DMA_CTL2_CH4TSEL_MPY << DMA_CTL2_R_CH4TSEL_BIT)
#define DMA_CTL2_R_CH4TSEL_DMA (DMA_CTL2_CH4TSEL_DMA << DMA_CTL2_R_CH4TSEL_BIT)
#define DMA_CTL2_R_CH4TSEL_EXTERNAL (DMA_CTL2_CH4TSEL_EXTERNAL << DMA_CTL2_R_CH4TSEL_BIT)
/*-----------*/

/*-----------*/
#define DMA_CTL2_R_CH5TSEL_BIT ((UBase_t) 8U)

#define DMA_CTL2_CH5TSEL_MASK ((UBase_t) 0x1FU)
#define DMA_CTL2_CH5TSEL_SW ((UBase_t) 0U)
#define DMA_CTL2_CH5TSEL_TA0CCR0 ((UBase_t) 1U)
#define DMA_CTL2_CH5TSEL_TA0CCR2 ((UBase_t) 2U)
#define DMA_CTL2_CH5TSEL_TA2CCR0 ((UBase_t) 3U)
#define DMA_CTL2_CH5TSEL_TA2CCR2 ((UBase_t) 4U)
#define DMA_CTL2_CH5TSEL_UCA0_RX ((UBase_t) 16U)
#define DMA_CTL2_CH5TSEL_UCA0_TX ((UBase_t) 17U)
#define DMA_CTL2_CH5TSEL_UCB0_RX ((UBase_t) 18U)
#define DMA_CTL2_CH5TSEL_UCB0_TX ((UBase_t) 19U)
#define DMA_CTL2_CH5TSEL_ADC12x ((UBase_t) 24U)
#define DMA_CTL2_CH5TSEL_MPY ((UBase_t) 29U)
#define DMA_CTL2_CH5TSEL_DMA ((UBase_t) 30U)
#define DMA_CTL2_CH5TSEL_EXTERNAL ((UBase_t) 31U)

#define DMA_CTL2_R_CH5TSEL_MASK (DMA_CTL2_CH5TSEL_MASK << DMA_CTL2_R_CH5TSEL_BIT)
#define DMA_CTL2_R_CH5TSEL_SW (DMA_CTL2_CH5TSEL_SW << DMA_CTL2_R_CH5TSEL_BIT)
#define DMA_CTL2_R_CH5TSEL_TA0CCR0 (DMA_CTL2_CH5TSEL_TA0CCR0 << DMA_CTL2_R_CH5TSEL_BIT)
#define DMA_CTL2_R_CH5TSEL_TA0CCR2 (DMA_CTL2_CH5TSEL_TA0CCR2 << DMA_CTL2_R_CH5TSEL_BIT)
#define DMA_CTL2_R_CH5TSEL_TA2CCR0 (DMA_CTL2_CH5TSEL_TA2CCR0 << DMA_CTL2_R_CH5TSEL_BIT)
#define DMA_CTL2_R_CH5TSEL_TA2CCR2 (DMA_CTL2_CH5TSEL_TA2CCR2 << DMA_CTL2_R_CH5TSEL_BIT)
#define DMA_CTL2_R_CH5TSEL_UCA0_RX (DMA_CTL2_CH5TSEL_UCA0_RX << DMA_CTL2_R_CH5TSEL_BIT)
#define DMA_CTL2_R_CH5TSEL_UCA0_TX (DMA_CTL2_CH5TSEL_UCA0_TX << DMA_CTL2_R_CH5TSEL_BIT)
#define DMA_CTL2_R_CH5TSEL_UCB0_RX (DMA_CTL2_CH5TSEL_UCB0_RX << DMA_CTL2_R_CH5TSEL_BIT)
#define DMA_CTL2_R_CH5TSEL_UCB0_TX (DMA_CTL2_CH5TSEL_UCB0_TX << DMA_CTL2_R_CH5TSEL_BIT)
#define DMA_CTL2_R_CH5TSEL_ADC12x (DMA_CTL2_CH5TSEL_ADC12x << DMA_CTL2_R_CH5TSEL_BIT)
#define DMA_CTL2_R_CH5TSEL_MPY (DMA_CTL2_CH5TSEL_MPY << DMA_CTL2_R_CH5TSEL_BIT)
#define DMA_CTL2_R_CH5TSEL_DMA (DMA_CTL2_CH5TSEL_DMA << DMA_CTL2_R_CH5TSEL_BIT)
#define DMA_CTL2_R_CH5TSEL_EXTERNAL (DMA_CTL2_CH5TSEL_EXTERNAL << DMA_CTL2_R_CH5TSEL_BIT)
/*-----------*/

#endif /* XDRIVER_MCU_DMA_PERIPHERAL_REGISTERDEFINES_XHEADER_DMA_REGISTERDEFINES_CTL2_H_ */
