/**
 *
 * @file CLOCK_RegisterDefines_CTL3.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 21 mar. 2023 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 21 mar. 2023     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_CLOCK_PERIPHERAL_REGISTERDEFINES_XHEADER_CLOCK_REGISTERDEFINES_CTL3_H_
#define XDRIVER_MCU_CLOCK_PERIPHERAL_REGISTERDEFINES_XHEADER_CLOCK_REGISTERDEFINES_CTL3_H_

#include "xDriver_MCU/CLOCK/Peripheral/xHeader/CLOCK_Enum.h"

/******************************************************************************************
 ************************************ 1 CTL3 *********************************************
 ******************************************************************************************/
/*-----------*/
#define CLOCK_CTL3_R_FLL_REFDIV_BIT ((UBase_t) 0U)

#define CLOCK_CTL3_FLL_REFDIV_MASK ((UBase_t) 0x07U)
#define CLOCK_CTL3_FLL_REFDIV_1 ((UBase_t) 0x00U)
#define CLOCK_CTL3_FLL_REFDIV_2 ((UBase_t) 0x01U)
#define CLOCK_CTL3_FLL_REFDIV_4 ((UBase_t) 0x02U)
#define CLOCK_CTL3_FLL_REFDIV_8 ((UBase_t) 0x03U)
#define CLOCK_CTL3_FLL_REFDIV_12 ((UBase_t) 0x04U)
#define CLOCK_CTL3_FLL_REFDIV_16 ((UBase_t) 0x05U)

#define CLOCK_CTL3_R_FLL_REFDIV_MASK (CLOCK_CTL3_FLL_REFDIV_MASK<< CLOCK_CTL3_R_FLL_REFDIV_BIT)
#define CLOCK_CTL3_R_FLL_REFDIV_1 (CLOCK_CTL3_FLL_REFDIV_1 << CLOCK_CTL3_R_FLL_REFDIV_BIT)
#define CLOCK_CTL3_R_FLL_REFDIV_2 (CLOCK_CTL3_FLL_REFDIV_2 << CLOCK_CTL3_R_FLL_REFDIV_BIT)
#define CLOCK_CTL3_R_FLL_REFDIV_4 (CLOCK_CTL3_FLL_REFDIV_4 << CLOCK_CTL3_R_FLL_REFDIV_BIT)
#define CLOCK_CTL3_R_FLL_REFDIV_8 (CLOCK_CTL3_FLL_REFDIV_8 << CLOCK_CTL3_R_FLL_REFDIV_BIT)
#define CLOCK_CTL3_R_FLL_REFDIV_12 (CLOCK_CTL3_FLL_REFDIV_12 << CLOCK_CTL3_R_FLL_REFDIV_BIT)
#define CLOCK_CTL3_R_FLL_REFDIV_16 (CLOCK_CTL3_FLL_REFDIV_16 << CLOCK_CTL3_R_FLL_REFDIV_BIT)
/*-----------*/

/*-----------*/
#define CLOCK_CTL3_R_FLL_SELREF_BIT ((UBase_t) 4U)

#define CLOCK_CTL3_FLL_SELREF_MASK ((UBase_t) 0x07U)
#define CLOCK_CTL3_FLL_SELREF_XT1CLK ((UBase_t) 0x00U)
#define CLOCK_CTL3_FLL_SELREF_XT1CLK_ALT1 ((UBase_t) 0x01U)
#define CLOCK_CTL3_FLL_SELREF_REFOCLK ((UBase_t) 0x02U)
#define CLOCK_CTL3_FLL_SELREF_REFOCLK_ALT1 ((UBase_t) 0x03U)
#define CLOCK_CTL3_FLL_SELREF_REFOCLK_ALT2 ((UBase_t) 0x04U)
#define CLOCK_CTL3_FLL_SELREF_XT2CLK ((UBase_t) 0x05U)
#define CLOCK_CTL3_FLL_SELREF_XT2CLK_ATL1 ((UBase_t) 0x06U)
#define CLOCK_CTL3_FLL_SELREF_XT2CLK_ATL2 ((UBase_t) 0x07U)

#define CLOCK_CTL3_R_FLL_SELREF_MASK (CLOCK_CTL3_FLL_SELREF_MASK<< CLOCK_CTL3_R_FLL_SELREF_BIT)
#define CLOCK_CTL3_R_FLL_SELREF_XT1CLK (CLOCK_CTL3_FLL_SELREF_XT1CLK<< CLOCK_CTL3_R_FLL_SELREF_BIT)
#define CLOCK_CTL3_R_FLL_SELREF_XT1CLK_ALT1 (CLOCK_CTL3_FLL_SELREF_XT1CLK_ALT1<< CLOCK_CTL3_R_FLL_SELREF_BIT)
#define CLOCK_CTL3_R_FLL_SELREF_REFOCLK (CLOCK_CTL3_FLL_SELREF_REFOCLK<< CLOCK_CTL3_R_FLL_SELREF_BIT)
#define CLOCK_CTL3_R_FLL_SELREF_REFOCLK_ALT1 (CLOCK_CTL3_FLL_SELREF_REFOCLK_ALT1<< CLOCK_CTL3_R_FLL_SELREF_BIT)
#define CLOCK_CTL3_R_FLL_SELREF_REFOCLK_ALT2 (CLOCK_CTL3_FLL_SELREF_REFOCLK_ALT2<< CLOCK_CTL3_R_FLL_SELREF_BIT)
#define CLOCK_CTL3_R_FLL_SELREF_XT2CLK (CLOCK_CTL3_FLL_SELREF_XT2CLK<< CLOCK_CTL3_R_FLL_SELREF_BIT)
#define CLOCK_CTL3_R_FLL_SELREF_XT2CLK_ATL1 (CLOCK_CTL3_FLL_SELREF_XT2CLK_ATL1<< CLOCK_CTL3_R_FLL_SELREF_BIT)
#define CLOCK_CTL3_R_FLL_SELREF_XT2CLK_ATL2 (CLOCK_CTL3_FLL_SELREF_XT2CLK_ATL2<< CLOCK_CTL3_R_FLL_SELREF_BIT)
/*-----------*/

#endif /* XDRIVER_MCU_CLOCK_PERIPHERAL_REGISTERDEFINES_XHEADER_CLOCK_REGISTERDEFINES_CTL3_H_ */
