/**
 *
 * @file CLOCK_RegisterDefines_CTL5.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 21 mar. 2023 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 21 mar. 2023     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_CLOCK_PERIPHERAL_REGISTERDEFINES_XHEADER_CLOCK_REGISTERDEFINES_CTL5_H_
#define XDRIVER_MCU_CLOCK_PERIPHERAL_REGISTERDEFINES_XHEADER_CLOCK_REGISTERDEFINES_CTL5_H_

#include "xDriver_MCU/CLOCK/Peripheral/xHeader/CLOCK_Enum.h"

/******************************************************************************************
 ************************************ 1 CTL5 *********************************************
 ******************************************************************************************/

/*-----------*/
#define CLOCK_CTL5_R_MCLK_DIV_BIT ((UBase_t) 0U)

#define CLOCK_CTL5_MCLK_DIV_MASK ((UBase_t) 0x07U)
#define CLOCK_CTL5_MCLK_DIV_1 ((UBase_t) 0x00U)
#define CLOCK_CTL5_MCLK_DIV_2 ((UBase_t) 0x01U)
#define CLOCK_CTL5_MCLK_DIV_4 ((UBase_t) 0x02U)
#define CLOCK_CTL5_MCLK_DIV_8 ((UBase_t) 0x03U)
#define CLOCK_CTL5_MCLK_DIV_16 ((UBase_t) 0x04U)
#define CLOCK_CTL5_MCLK_DIV_32 ((UBase_t) 0x05U)

#define CLOCK_CTL5_R_MCLK_DIV_MASK (CLOCK_CTL5_MCLK_DIV_MASK<< CLOCK_CTL5_R_MCLK_DIV_BIT)
#define CLOCK_CTL5_R_MCLK_DIV_1 (CLOCK_CTL5_MCLK_DIV_1 << CLOCK_CTL5_R_MCLK_DIV_BIT)
#define CLOCK_CTL5_R_MCLK_DIV_2 (CLOCK_CTL5_MCLK_DIV_2 << CLOCK_CTL5_R_MCLK_DIV_BIT)
#define CLOCK_CTL5_R_MCLK_DIV_4 (CLOCK_CTL5_MCLK_DIV_4 << CLOCK_CTL5_R_MCLK_DIV_BIT)
#define CLOCK_CTL5_R_MCLK_DIV_8 (CLOCK_CTL5_MCLK_DIV_8 << CLOCK_CTL5_R_MCLK_DIV_BIT)
#define CLOCK_CTL5_R_MCLK_DIV_16 (CLOCK_CTL5_MCLK_DIV_16 << CLOCK_CTL5_R_MCLK_DIV_BIT)
#define CLOCK_CTL5_R_MCLK_DIV_32 (CLOCK_CTL5_MCLK_DIV_32 << CLOCK_CTL5_R_MCLK_DIV_BIT)
/*-----------*/

/*-----------*/
#define CLOCK_CTL5_R_SMCLK_DIV_BIT ((UBase_t) 4U)

#define CLOCK_CTL5_SMCLK_DIV_MASK ((UBase_t) 0x07U)
#define CLOCK_CTL5_SMCLK_DIV_1 ((UBase_t) 0x00U)
#define CLOCK_CTL5_SMCLK_DIV_2 ((UBase_t) 0x01U)
#define CLOCK_CTL5_SMCLK_DIV_4 ((UBase_t) 0x02U)
#define CLOCK_CTL5_SMCLK_DIV_8 ((UBase_t) 0x03U)
#define CLOCK_CTL5_SMCLK_DIV_16 ((UBase_t) 0x04U)
#define CLOCK_CTL5_SMCLK_DIV_32 ((UBase_t) 0x05U)

#define CLOCK_CTL5_R_SMCLK_DIV_MASK (CLOCK_CTL5_SMCLK_DIV_MASK<< CLOCK_CTL5_R_SMCLK_DIV_BIT)
#define CLOCK_CTL5_R_SMCLK_DIV_1 (CLOCK_CTL5_SMCLK_DIV_1 << CLOCK_CTL5_R_SMCLK_DIV_BIT)
#define CLOCK_CTL5_R_SMCLK_DIV_2 (CLOCK_CTL5_SMCLK_DIV_2 << CLOCK_CTL5_R_SMCLK_DIV_BIT)
#define CLOCK_CTL5_R_SMCLK_DIV_4 (CLOCK_CTL5_SMCLK_DIV_4 << CLOCK_CTL5_R_SMCLK_DIV_BIT)
#define CLOCK_CTL5_R_SMCLK_DIV_8 (CLOCK_CTL5_SMCLK_DIV_8 << CLOCK_CTL5_R_SMCLK_DIV_BIT)
#define CLOCK_CTL5_R_SMCLK_DIV_16 (CLOCK_CTL5_SMCLK_DIV_16 << CLOCK_CTL5_R_SMCLK_DIV_BIT)
#define CLOCK_CTL5_R_SMCLK_DIV_32 (CLOCK_CTL5_SMCLK_DIV_32 << CLOCK_CTL5_R_SMCLK_DIV_BIT)
/*-----------*/

/*-----------*/
#define CLOCK_CTL5_R_ACLK_DIV_BIT ((UBase_t) 8U)

#define CLOCK_CTL5_ACLK_DIV_MASK ((UBase_t) 0x07U)
#define CLOCK_CTL5_ACLK_DIV_1 ((UBase_t) 0x00U)
#define CLOCK_CTL5_ACLK_DIV_2 ((UBase_t) 0x01U)
#define CLOCK_CTL5_ACLK_DIV_4 ((UBase_t) 0x02U)
#define CLOCK_CTL5_ACLK_DIV_8 ((UBase_t) 0x03U)
#define CLOCK_CTL5_ACLK_DIV_16 ((UBase_t) 0x04U)
#define CLOCK_CTL5_ACLK_DIV_32 ((UBase_t) 0x05U)

#define CLOCK_CTL5_R_ACLK_DIV_MASK (CLOCK_CTL5_ACLK_DIV_MASK<< CLOCK_CTL5_R_ACLK_DIV_BIT)
#define CLOCK_CTL5_R_ACLK_DIV_1 (CLOCK_CTL5_ACLK_DIV_1 << CLOCK_CTL5_R_ACLK_DIV_BIT)
#define CLOCK_CTL5_R_ACLK_DIV_2 (CLOCK_CTL5_ACLK_DIV_2 << CLOCK_CTL5_R_ACLK_DIV_BIT)
#define CLOCK_CTL5_R_ACLK_DIV_4 (CLOCK_CTL5_ACLK_DIV_4 << CLOCK_CTL5_R_ACLK_DIV_BIT)
#define CLOCK_CTL5_R_ACLK_DIV_8 (CLOCK_CTL5_ACLK_DIV_8 << CLOCK_CTL5_R_ACLK_DIV_BIT)
#define CLOCK_CTL5_R_ACLK_DIV_16 (CLOCK_CTL5_ACLK_DIV_16 << CLOCK_CTL5_R_ACLK_DIV_BIT)
#define CLOCK_CTL5_R_ACLK_DIV_32 (CLOCK_CTL5_ACLK_DIV_32 << CLOCK_CTL5_R_ACLK_DIV_BIT)
/*-----------*/

/*-----------*/
#define CLOCK_CTL5_R_ACLK_PINDIV_BIT ((UBase_t) 12U)

#define CLOCK_CTL5_ACLK_PINDIV_MASK ((UBase_t) 0x07U)
#define CLOCK_CTL5_ACLK_PINDIV_1 ((UBase_t) 0x00U)
#define CLOCK_CTL5_ACLK_PINDIV_2 ((UBase_t) 0x01U)
#define CLOCK_CTL5_ACLK_PINDIV_4 ((UBase_t) 0x02U)
#define CLOCK_CTL5_ACLK_PINDIV_8 ((UBase_t) 0x03U)
#define CLOCK_CTL5_ACLK_PINDIV_16 ((UBase_t) 0x04U)
#define CLOCK_CTL5_ACLK_PINDIV_32 ((UBase_t) 0x05U)

#define CLOCK_CTL5_R_ACLK_PINDIV_MASK (CLOCK_CTL5_ACLK_PINDIV_MASK<< CLOCK_CTL5_R_ACLK_PINDIV_BIT)
#define CLOCK_CTL5_R_ACLK_PINDIV_1 (CLOCK_CTL5_ACLK_PINDIV_1 << CLOCK_CTL5_R_ACLK_PINDIV_BIT)
#define CLOCK_CTL5_R_ACLK_PINDIV_2 (CLOCK_CTL5_ACLK_PINDIV_2 << CLOCK_CTL5_R_ACLK_PINDIV_BIT)
#define CLOCK_CTL5_R_ACLK_PINDIV_4 (CLOCK_CTL5_ACLK_PINDIV_4 << CLOCK_CTL5_R_ACLK_PINDIV_BIT)
#define CLOCK_CTL5_R_ACLK_PINDIV_8 (CLOCK_CTL5_ACLK_PINDIV_8 << CLOCK_CTL5_R_ACLK_PINDIV_BIT)
#define CLOCK_CTL5_R_ACLK_PINDIV_16 (CLOCK_CTL5_ACLK_PINDIV_16 << CLOCK_CTL5_R_ACLK_PINDIV_BIT)
#define CLOCK_CTL5_R_ACLK_PINDIV_32 (CLOCK_CTL5_ACLK_PINDIV_32 << CLOCK_CTL5_R_ACLK_PINDIV_BIT)
/*-----------*/

#endif /* XDRIVER_MCU_CLOCK_PERIPHERAL_REGISTERDEFINES_XHEADER_CLOCK_REGISTERDEFINES_CTL5_H_ */
