/**
 *
 * @file CLOCK_RegisterDefines_CTL4.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 21 mar. 2023 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 21 mar. 2023     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_CLOCK_PERIPHERAL_REGISTERDEFINES_XHEADER_CLOCK_REGISTERDEFINES_CTL4_H_
#define XDRIVER_MCU_CLOCK_PERIPHERAL_REGISTERDEFINES_XHEADER_CLOCK_REGISTERDEFINES_CTL4_H_

#include "xDriver_MCU/CLOCK/Peripheral/xHeader/CLOCK_Enum.h"

/******************************************************************************************
 ************************************ 1 CTL4 *********************************************
 ******************************************************************************************/
/*-----------*/
#define CLOCK_CTL4_R_MCLK_SEL_BIT ((UBase_t) 0U)

#define CLOCK_CTL4_MCLK_SEL_MASK ((UBase_t) 0x07U)
#define CLOCK_CTL4_MCLK_SEL_XT1CLK ((UBase_t) 0x00U)
#define CLOCK_CTL4_MCLK_SEL_VLOCLK ((UBase_t) 0x01U)
#define CLOCK_CTL4_MCLK_SEL_REFOCLK ((UBase_t) 0x02U)
#define CLOCK_CTL4_MCLK_SEL_DCOCLK ((UBase_t) 0x03U)
#define CLOCK_CTL4_MCLK_SEL_DCOCLKDIV ((UBase_t) 0x04U)

#define CLOCK_CTL4_R_MCLK_SEL_MASK (CLOCK_CTL4_MCLK_SEL_MASK<< CLOCK_CTL4_R_MCLK_SEL_BIT)
#define CLOCK_CTL4_R_MCLK_SEL_XT1CLK (CLOCK_CTL4_MCLK_SEL_XT1CLK<< CLOCK_CTL4_R_MCLK_SEL_BIT)
#define CLOCK_CTL4_R_MCLK_SEL_VLOCLK (CLOCK_CTL4_MCLK_SEL_VLOCLK<< CLOCK_CTL4_R_MCLK_SEL_BIT)
#define CLOCK_CTL4_R_MCLK_SEL_REFOCLK (CLOCK_CTL4_MCLK_SEL_REFOCLK<< CLOCK_CTL4_R_MCLK_SEL_BIT)
#define CLOCK_CTL4_R_MCLK_SEL_DCOCLK (CLOCK_CTL4_MCLK_SEL_DCOCLK<< CLOCK_CTL4_R_MCLK_SEL_BIT)
#define CLOCK_CTL4_R_MCLK_SEL_DCOCLKDIV (CLOCK_CTL4_MCLK_SEL_DCOCLKDIV<< CLOCK_CTL4_R_MCLK_SEL_BIT)
/*-----------*/

/*-----------*/
#define CLOCK_CTL4_R_SMCLK_SEL_BIT ((UBase_t) 4U)

#define CLOCK_CTL4_SMCLK_SEL_MASK ((UBase_t) 0x07U)
#define CLOCK_CTL4_SMCLK_SEL_XT1CLK ((UBase_t) 0x00U)
#define CLOCK_CTL4_SMCLK_SEL_VLOCLK ((UBase_t) 0x01U)
#define CLOCK_CTL4_SMCLK_SEL_REFOCLK ((UBase_t) 0x02U)
#define CLOCK_CTL4_SMCLK_SEL_DCOCLK ((UBase_t) 0x03U)
#define CLOCK_CTL4_SMCLK_SEL_DCOCLKDIV ((UBase_t) 0x04U)

#define CLOCK_CTL4_R_SMCLK_SEL_MASK (CLOCK_CTL4_SMCLK_SEL_MASK<< CLOCK_CTL4_R_SMCLK_SEL_BIT)
#define CLOCK_CTL4_R_SMCLK_SEL_XT1CLK (CLOCK_CTL4_SMCLK_SEL_XT1CLK<< CLOCK_CTL4_R_SMCLK_SEL_BIT)
#define CLOCK_CTL4_R_SMCLK_SEL_VLOCLK (CLOCK_CTL4_SMCLK_SEL_VLOCLK<< CLOCK_CTL4_R_SMCLK_SEL_BIT)
#define CLOCK_CTL4_R_SMCLK_SEL_REFOCLK (CLOCK_CTL4_SMCLK_SEL_REFOCLK<< CLOCK_CTL4_R_SMCLK_SEL_BIT)
#define CLOCK_CTL4_R_SMCLK_SEL_DCOCLK (CLOCK_CTL4_SMCLK_SEL_DCOCLK<< CLOCK_CTL4_R_SMCLK_SEL_BIT)
#define CLOCK_CTL4_R_SMCLK_SEL_DCOCLKDIV (CLOCK_CTL4_SMCLK_SEL_DCOCLKDIV<< CLOCK_CTL4_R_SMCLK_SEL_BIT)
/*-----------*/

/*-----------*/
#define CLOCK_CTL4_R_ACLK_SEL_BIT ((UBase_t) 8U)

#define CLOCK_CTL4_ACLK_SEL_MASK ((UBase_t) 0x07U)
#define CLOCK_CTL4_ACLK_SEL_XT1CLK ((UBase_t) 0x00U)
#define CLOCK_CTL4_ACLK_SEL_VLOCLK ((UBase_t) 0x01U)
#define CLOCK_CTL4_ACLK_SEL_REFOCLK ((UBase_t) 0x02U)
#define CLOCK_CTL4_ACLK_SEL_DCOCLK ((UBase_t) 0x03U)
#define CLOCK_CTL4_ACLK_SEL_DCOCLKDIV ((UBase_t) 0x04U)

#define CLOCK_CTL4_R_ACLK_SEL_MASK (CLOCK_CTL4_ACLK_SEL_MASK<< CLOCK_CTL4_R_ACLK_SEL_BIT)
#define CLOCK_CTL4_R_ACLK_SEL_XT1CLK (CLOCK_CTL4_ACLK_SEL_XT1CLK<< CLOCK_CTL4_R_ACLK_SEL_BIT)
#define CLOCK_CTL4_R_ACLK_SEL_VLOCLK (CLOCK_CTL4_ACLK_SEL_VLOCLK<< CLOCK_CTL4_R_ACLK_SEL_BIT)
#define CLOCK_CTL4_R_ACLK_SEL_REFOCLK (CLOCK_CTL4_ACLK_SEL_REFOCLK<< CLOCK_CTL4_R_ACLK_SEL_BIT)
#define CLOCK_CTL4_R_ACLK_SEL_DCOCLK (CLOCK_CTL4_ACLK_SEL_DCOCLK<< CLOCK_CTL4_R_ACLK_SEL_BIT)
#define CLOCK_CTL4_R_ACLK_SEL_DCOCLKDIV (CLOCK_CTL4_ACLK_SEL_DCOCLKDIV<< CLOCK_CTL4_R_ACLK_SEL_BIT)
/*-----------*/



#endif /* XDRIVER_MCU_CLOCK_PERIPHERAL_REGISTERDEFINES_XHEADER_CLOCK_REGISTERDEFINES_CTL4_H_ */
