/**
 *
 * @file CLOCK_RegisterDefines_CTL0.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 21 mar. 2023 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 21 mar. 2023     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef XDRIVER_MCU_CLOCK_PERIPHERAL_REGISTERDEFINES_XHEADER_CLOCK_REGISTERDEFINES_CTL0_H_
#define XDRIVER_MCU_CLOCK_PERIPHERAL_REGISTERDEFINES_XHEADER_CLOCK_REGISTERDEFINES_CTL0_H_

#include "xDriver_MCU/CLOCK/Peripheral/xHeader/CLOCK_Enum.h"

/******************************************************************************************
 ************************************ 1 CTL0 *********************************************
 ******************************************************************************************/
/*-----------*/
#define CLOCK_CTL0_R_MOD_BIT ((UBase_t) 3U)

#define CLOCK_CTL0_MOD_MASK ((UBase_t) 0x1FU)
#define CLOCK_CTL0_MOD_0 ((UBase_t) 0x00U)
#define CLOCK_CTL0_MOD_1 ((UBase_t) 0x01U)
#define CLOCK_CTL0_MOD_2 ((UBase_t) 0x02U)
#define CLOCK_CTL0_MOD_3 ((UBase_t) 0x03U)
#define CLOCK_CTL0_MOD_4 ((UBase_t) 0x04U)
#define CLOCK_CTL0_MOD_5 ((UBase_t) 0x05U)
#define CLOCK_CTL0_MOD_6 ((UBase_t) 0x06U)
#define CLOCK_CTL0_MOD_7 ((UBase_t) 0x07U)
#define CLOCK_CTL0_MOD_8 ((UBase_t) 0x08U)
#define CLOCK_CTL0_MOD_9 ((UBase_t) 0x09U)
#define CLOCK_CTL0_MOD_10 ((UBase_t) 0x0AU)
#define CLOCK_CTL0_MOD_11 ((UBase_t) 0x0BU)
#define CLOCK_CTL0_MOD_12 ((UBase_t) 0x0CU)
#define CLOCK_CTL0_MOD_13 ((UBase_t) 0x0DU)
#define CLOCK_CTL0_MOD_14 ((UBase_t) 0x0EU)
#define CLOCK_CTL0_MOD_15 ((UBase_t) 0x0FU)
#define CLOCK_CTL0_MOD_16 ((UBase_t) 0x10U)
#define CLOCK_CTL0_MOD_17 ((UBase_t) 0x11U)
#define CLOCK_CTL0_MOD_18 ((UBase_t) 0x12U)
#define CLOCK_CTL0_MOD_19 ((UBase_t) 0x13U)
#define CLOCK_CTL0_MOD_20 ((UBase_t) 0x14U)
#define CLOCK_CTL0_MOD_21 ((UBase_t) 0x15U)
#define CLOCK_CTL0_MOD_22 ((UBase_t) 0x16U)
#define CLOCK_CTL0_MOD_23 ((UBase_t) 0x17U)
#define CLOCK_CTL0_MOD_24 ((UBase_t) 0x18U)
#define CLOCK_CTL0_MOD_25 ((UBase_t) 0x19U)
#define CLOCK_CTL0_MOD_26 ((UBase_t) 0x1AU)
#define CLOCK_CTL0_MOD_27 ((UBase_t) 0x1BU)
#define CLOCK_CTL0_MOD_28 ((UBase_t) 0x1CU)
#define CLOCK_CTL0_MOD_29 ((UBase_t) 0x1DU)
#define CLOCK_CTL0_MOD_30 ((UBase_t) 0x1EU)
#define CLOCK_CTL0_MOD_31 ((UBase_t) 0x1FU)

#define CLOCK_CTL0_R_MOD_MASK (CLOCK_CTL0_MOD_MASK<< CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_0 (CLOCK_CTL0_MOD_0 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_1 (CLOCK_CTL0_MOD_1 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_2 (CLOCK_CTL0_MOD_2 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_3 (CLOCK_CTL0_MOD_3 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_4 (CLOCK_CTL0_MOD_4 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_5 (CLOCK_CTL0_MOD_5 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_6 (CLOCK_CTL0_MOD_6 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_7 (CLOCK_CTL0_MOD_7 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_8 (CLOCK_CTL0_MOD_8 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_9 (CLOCK_CTL0_MOD_9 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_10 (CLOCK_CTL0_MOD_10 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_11 (CLOCK_CTL0_MOD_11 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_12 (CLOCK_CTL0_MOD_12 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_13 (CLOCK_CTL0_MOD_13 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_14 (CLOCK_CTL0_MOD_14 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_15 (CLOCK_CTL0_MOD_15 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_16 (CLOCK_CTL0_MOD_16 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_17 (CLOCK_CTL0_MOD_17 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_18 (CLOCK_CTL0_MOD_18 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_19 (CLOCK_CTL0_MOD_19 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_20 (CLOCK_CTL0_MOD_20 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_21 (CLOCK_CTL0_MOD_21 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_22 (CLOCK_CTL0_MOD_22 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_23 (CLOCK_CTL0_MOD_23 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_24 (CLOCK_CTL0_MOD_24 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_25 (CLOCK_CTL0_MOD_25 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_26 (CLOCK_CTL0_MOD_26 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_27 (CLOCK_CTL0_MOD_27 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_28 (CLOCK_CTL0_MOD_28 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_29 (CLOCK_CTL0_MOD_29 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_30 (CLOCK_CTL0_MOD_30 << CLOCK_CTL0_R_MOD_BIT)
#define CLOCK_CTL0_R_MOD_31 (CLOCK_CTL0_MOD_31 << CLOCK_CTL0_R_MOD_BIT)
/*-----------*/

/*-----------*/
#define CLOCK_CTL0_R_DCO_BIT ((UBase_t) 8U)

#define CLOCK_CTL0_DCO_MASK ((UBase_t) 0x1FU)
#define CLOCK_CTL0_DCO_0 ((UBase_t) 0x00U)
#define CLOCK_CTL0_DCO_1 ((UBase_t) 0x01U)
#define CLOCK_CTL0_DCO_2 ((UBase_t) 0x02U)
#define CLOCK_CTL0_DCO_3 ((UBase_t) 0x03U)
#define CLOCK_CTL0_DCO_4 ((UBase_t) 0x04U)
#define CLOCK_CTL0_DCO_5 ((UBase_t) 0x05U)
#define CLOCK_CTL0_DCO_6 ((UBase_t) 0x06U)
#define CLOCK_CTL0_DCO_7 ((UBase_t) 0x07U)
#define CLOCK_CTL0_DCO_8 ((UBase_t) 0x08U)
#define CLOCK_CTL0_DCO_9 ((UBase_t) 0x09U)
#define CLOCK_CTL0_DCO_10 ((UBase_t) 0x0AU)
#define CLOCK_CTL0_DCO_11 ((UBase_t) 0x0BU)
#define CLOCK_CTL0_DCO_12 ((UBase_t) 0x0CU)
#define CLOCK_CTL0_DCO_13 ((UBase_t) 0x0DU)
#define CLOCK_CTL0_DCO_14 ((UBase_t) 0x0EU)
#define CLOCK_CTL0_DCO_15 ((UBase_t) 0x0FU)
#define CLOCK_CTL0_DCO_16 ((UBase_t) 0x10U)
#define CLOCK_CTL0_DCO_17 ((UBase_t) 0x11U)
#define CLOCK_CTL0_DCO_18 ((UBase_t) 0x12U)
#define CLOCK_CTL0_DCO_19 ((UBase_t) 0x13U)
#define CLOCK_CTL0_DCO_20 ((UBase_t) 0x14U)
#define CLOCK_CTL0_DCO_21 ((UBase_t) 0x15U)
#define CLOCK_CTL0_DCO_22 ((UBase_t) 0x16U)
#define CLOCK_CTL0_DCO_23 ((UBase_t) 0x17U)
#define CLOCK_CTL0_DCO_24 ((UBase_t) 0x18U)
#define CLOCK_CTL0_DCO_25 ((UBase_t) 0x19U)
#define CLOCK_CTL0_DCO_26 ((UBase_t) 0x1AU)
#define CLOCK_CTL0_DCO_27 ((UBase_t) 0x1BU)
#define CLOCK_CTL0_DCO_28 ((UBase_t) 0x1CU)
#define CLOCK_CTL0_DCO_29 ((UBase_t) 0x1DU)
#define CLOCK_CTL0_DCO_30 ((UBase_t) 0x1EU)
#define CLOCK_CTL0_DCO_31 ((UBase_t) 0x1FU)

#define CLOCK_CTL0_R_DCO_MASK (CLOCK_CTL0_DCO_MASK<< CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_0 (CLOCK_CTL0_DCO_0 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_1 (CLOCK_CTL0_DCO_1 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_2 (CLOCK_CTL0_DCO_2 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_3 (CLOCK_CTL0_DCO_3 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_4 (CLOCK_CTL0_DCO_4 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_5 (CLOCK_CTL0_DCO_5 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_6 (CLOCK_CTL0_DCO_6 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_7 (CLOCK_CTL0_DCO_7 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_8 (CLOCK_CTL0_DCO_8 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_9 (CLOCK_CTL0_DCO_9 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_10 (CLOCK_CTL0_DCO_10 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_11 (CLOCK_CTL0_DCO_11 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_12 (CLOCK_CTL0_DCO_12 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_13 (CLOCK_CTL0_DCO_13 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_14 (CLOCK_CTL0_DCO_14 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_15 (CLOCK_CTL0_DCO_15 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_16 (CLOCK_CTL0_DCO_16 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_17 (CLOCK_CTL0_DCO_17 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_18 (CLOCK_CTL0_DCO_18 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_19 (CLOCK_CTL0_DCO_19 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_20 (CLOCK_CTL0_DCO_20 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_21 (CLOCK_CTL0_DCO_21 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_22 (CLOCK_CTL0_DCO_22 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_23 (CLOCK_CTL0_DCO_23 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_24 (CLOCK_CTL0_DCO_24 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_25 (CLOCK_CTL0_DCO_25 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_26 (CLOCK_CTL0_DCO_26 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_27 (CLOCK_CTL0_DCO_27 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_28 (CLOCK_CTL0_DCO_28 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_29 (CLOCK_CTL0_DCO_29 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_30 (CLOCK_CTL0_DCO_30 << CLOCK_CTL0_R_DCO_BIT)
#define CLOCK_CTL0_R_DCO_31 (CLOCK_CTL0_DCO_31 << CLOCK_CTL0_R_DCO_BIT)
/*-----------*/

#endif /* XDRIVER_MCU_CLOCK_PERIPHERAL_REGISTERDEFINES_XHEADER_CLOCK_REGISTERDEFINES_CTL0_H_ */
